/**
 * Script zum Löschen aller automatisch generierten TODOs
 *
 * Verwendung:
 *   node scripts/deleteAutoGeneratedTodos.js
 *
 * Optional mit --dry-run Flag um nur anzuzeigen was gelöscht werden würde:
 *   node scripts/deleteAutoGeneratedTodos.js --dry-run
 */

const mongoose = require('mongoose');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

// Todo Model importieren
const Todo = require('../src/models/Todo');

const isDryRun = process.argv.includes('--dry-run');

async function deleteAutoGeneratedTodos() {
  try {
    // Verbindung zur Datenbank herstellen
    const mongoUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/berater-app';
    console.log('Verbinde mit Datenbank...');
    await mongoose.connect(mongoUri);
    console.log('Datenbankverbindung hergestellt.\n');

    // Zähle automatisch generierte TODOs
    const count = await Todo.countDocuments({ isAutoGenerated: true });
    console.log(`Gefundene automatisch generierte TODOs: ${count}`);

    if (count === 0) {
      console.log('\nKeine automatisch generierten TODOs zum Löschen gefunden.');
      await mongoose.disconnect();
      return;
    }

    // Zeige Details der zu löschenden TODOs
    const todosToDelete = await Todo.find({ isAutoGenerated: true })
      .select('title autoGenerationType createdAt berater')
      .populate('berater', 'firstName lastName email')
      .lean();

    console.log('\nZu löschende TODOs:');
    console.log('─'.repeat(80));

    // Gruppiere nach Typ
    const byType = {};
    todosToDelete.forEach(todo => {
      const type = todo.autoGenerationType || 'unknown';
      if (!byType[type]) byType[type] = [];
      byType[type].push(todo);
    });

    for (const [type, todos] of Object.entries(byType)) {
      console.log(`\n[${type}] - ${todos.length} TODOs:`);
      todos.slice(0, 5).forEach(todo => {
        const beraterName = todo.berater
          ? `${todo.berater.firstName} ${todo.berater.lastName}`
          : 'Unbekannt';
        console.log(`  - "${todo.title}" (Berater: ${beraterName})`);
      });
      if (todos.length > 5) {
        console.log(`  ... und ${todos.length - 5} weitere`);
      }
    }

    console.log('\n' + '─'.repeat(80));

    if (isDryRun) {
      console.log('\n[DRY-RUN] Keine Änderungen vorgenommen.');
      console.log('Führen Sie das Script ohne --dry-run aus, um die TODOs zu löschen.');
    } else {
      // Lösche alle automatisch generierten TODOs
      const result = await Todo.deleteMany({ isAutoGenerated: true });
      console.log(`\n✓ ${result.deletedCount} automatisch generierte TODOs erfolgreich gelöscht.`);
    }

    await mongoose.disconnect();
    console.log('\nDatenbankverbindung geschlossen.');

  } catch (error) {
    console.error('Fehler beim Löschen der TODOs:', error);
    process.exit(1);
  }
}

// Script ausführen
deleteAutoGeneratedTodos();
