/**
 * Migration Script: Reminders zu TODOs
 *
 * Dieses Script:
 * 1. Löscht alle alten Reminders aus der Reminder-Collection
 * 2. Löscht alle automatisch generierten TODOs (contract_expiring)
 * 3. Erstellt neue TODOs basierend auf dem benutzerdefinierten Erinnerungswert (X Tage)
 *
 * Ausführung:
 *   node scripts/migrateRemindersToTodos.js           # Normale Ausführung
 *   node scripts/migrateRemindersToTodos.js --dry-run # Nur Vorschau, keine Änderungen
 */

const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });
const mongoose = require('mongoose');
const connectDB = require('../src/config/database');

// Models
const Reminder = require('../src/models/Reminder');
const Todo = require('../src/models/Todo');
const Contract = require('../src/models/Contract');
const User = require('../src/models/User');
const Customer = require('../src/models/Customer'); // Für populate

const isDryRun = process.argv.includes('--dry-run');

async function migrate() {
  try {
    console.log('='.repeat(60));
    console.log('Migration: Reminders zu TODOs');
    console.log('='.repeat(60));

    if (isDryRun) {
      console.log('\n⚠️  DRY-RUN Modus - Keine Änderungen werden durchgeführt\n');
    }

    // Verbinde zur Datenbank
    await connectDB();
    console.log('✅ Datenbankverbindung hergestellt\n');

    // 1. Zähle und lösche alte Reminders
    console.log('--- Schritt 1: Alte Reminders entfernen ---');
    const reminderCount = await Reminder.countDocuments();
    console.log(`Gefundene Reminders: ${reminderCount}`);

    if (!isDryRun && reminderCount > 0) {
      await Reminder.deleteMany({});
      console.log(`✅ ${reminderCount} Reminders gelöscht`);
    }

    // 2. Zähle und lösche alte auto-generierte TODOs
    console.log('\n--- Schritt 2: Alte auto-generierte TODOs entfernen ---');
    const oldTodoCount = await Todo.countDocuments({
      isAutoGenerated: true,
      autoGenerationType: 'contract_expiring'
    });
    console.log(`Gefundene auto-generierte TODOs: ${oldTodoCount}`);

    if (!isDryRun && oldTodoCount > 0) {
      await Todo.deleteMany({
        isAutoGenerated: true,
        autoGenerationType: 'contract_expiring'
      });
      console.log(`✅ ${oldTodoCount} alte TODOs gelöscht`);
    }

    // 3. Erstelle neue TODOs für alle Nutzer
    console.log('\n--- Schritt 3: Neue TODOs erstellen ---');

    const today = new Date();
    today.setHours(0, 0, 0, 0);

    // Hole alle aktiven Berater
    const beraters = await User.find({
      role: 'berater',
      isActive: true,
      isBlocked: false
    });
    console.log(`Aktive Berater gefunden: ${beraters.length}\n`);

    let totalCreated = 0;
    let totalSkipped = 0;

    for (const berater of beraters) {
      const reminderDays = berater.settings?.reminderDays?.custom || 30;

      // Berechne das Zieldatum basierend auf Benutzereinstellung
      const futureDate = new Date(today);
      futureDate.setDate(futureDate.getDate() + reminderDays);

      // Finde alle aktiven Verträge die innerhalb des Zeitraums ablaufen
      const expiringContracts = await Contract.find({
        beraterId: berater._id,
        status: 'active',
        endDate: {
          $gte: today,
          $lte: futureDate
        }
      }).populate('customerId', 'firstName lastName');

      let beraterCreated = 0;

      for (const contract of expiringContracts) {
        if (!contract.customerId) {
          totalSkipped++;
          continue;
        }

        const daysUntilExpiry = Math.ceil((contract.endDate - today) / (1000 * 60 * 60 * 24));

        // Priorität basierend auf prozentualem Anteil
        const percentRemaining = (daysUntilExpiry / reminderDays) * 100;
        const priority = percentRemaining <= 33 ? 'high' : percentRemaining <= 66 ? 'medium' : 'low';

        const todoData = {
          beraterId: berater._id,
          title: `Vertrag ${contract.contractNumber} läuft ab`,
          description: `Der Vertrag von ${contract.customerId.firstName} ${contract.customerId.lastName} läuft in ${daysUntilExpiry} Tagen ab. Bitte Verlängerung oder Kündigung vorbereiten.`,
          status: 'open',
          priority,
          dueDate: contract.endDate,
          relatedCustomerId: contract.customerId._id,
          relatedContractId: contract._id,
          isAutoGenerated: true,
          autoGenerationType: 'contract_expiring'
        };

        if (!isDryRun) {
          await Todo.create(todoData);
        }

        beraterCreated++;
        totalCreated++;
      }

      if (beraterCreated > 0 || expiringContracts.length > 0) {
        console.log(`👤 ${berater.email}: ${beraterCreated} TODOs erstellt (Einstellung: ${reminderDays} Tage, ${expiringContracts.length} ablaufende Verträge)`);
      }
    }

    // Zusammenfassung
    console.log('\n' + '='.repeat(60));
    console.log('ZUSAMMENFASSUNG');
    console.log('='.repeat(60));
    console.log(`Reminders gelöscht:        ${isDryRun ? `${reminderCount} (würden gelöscht)` : reminderCount}`);
    console.log(`Alte TODOs gelöscht:       ${isDryRun ? `${oldTodoCount} (würden gelöscht)` : oldTodoCount}`);
    console.log(`Neue TODOs erstellt:       ${isDryRun ? `${totalCreated} (würden erstellt)` : totalCreated}`);
    console.log(`Übersprungen (kein Kunde): ${totalSkipped}`);
    console.log('='.repeat(60));

    if (isDryRun) {
      console.log('\n💡 Führe ohne --dry-run aus, um die Änderungen durchzuführen');
    } else {
      console.log('\n✅ Migration erfolgreich abgeschlossen!');
    }

  } catch (error) {
    console.error('\n❌ Fehler bei der Migration:', error);
    process.exit(1);
  } finally {
    await mongoose.connection.close();
    console.log('\n🔌 Datenbankverbindung geschlossen');
    process.exit(0);
  }
}

// Script starten
migrate();
