const Todo = require('../models/Todo');
const TodoTopic = require('../models/TodoTopic');
const Contract = require('../models/Contract');
const User = require('../models/User');
const path = require('path');
const fs = require('fs').promises;

// Standard-Themen die für jeden neuen Benutzer erstellt werden
const DEFAULT_TOPICS = [
  'Zählerablesung',
  'Kündigung',
  'Rechnungsklärung',
  'Anmeldung',
  'Empfehlung',
  'Vertragsbestätigung'
];

// @desc    Get all todos
// @route   GET /api/todos
// @access  Private
exports.getTodos = async (req, res, next) => {
  try {
    const { status, priority, search, page = 1, limit = 50 } = req.query;

    const filter = { beraterId: req.user._id, isSupportTicket: { $ne: true } };

    if (status) filter.status = status;
    if (priority) filter.priority = priority;
    if (search) {
      filter.$or = [
        { title: { $regex: search, $options: 'i' } },
        { description: { $regex: search, $options: 'i' } }
      ];
    }

    const skip = (page - 1) * limit;
    const total = await Todo.countDocuments(filter);

    const todos = await Todo.find(filter)
      .populate('relatedCustomerId', 'firstName lastName customerNumber')
      .populate('relatedContractId', 'contractNumber startDate endDate')
      .populate('relatedMeterId', 'meterNumber type')
      .sort({ dueDate: 1, createdAt: -1 })
      .limit(parseInt(limit))
      .skip(skip)
      .lean();

    res.status(200).json({
      success: true,
      data: todos,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total,
        pages: Math.ceil(total / limit)
      }
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get single todo
// @route   GET /api/todos/:id
// @access  Private
exports.getTodo = async (req, res, next) => {
  try {
    const todo = await Todo.findOne({
      _id: req.params.id,
      beraterId: req.user._id
    })
      .populate('relatedCustomerId', 'firstName lastName customerNumber')
      .populate('relatedContractId', 'contractNumber startDate endDate')
      .populate('relatedMeterId', 'meterNumber type');

    if (!todo) {
      return res.status(404).json({
        success: false,
        message: 'TODO nicht gefunden'
      });
    }

    res.status(200).json({
      success: true,
      data: todo
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Create todo
// @route   POST /api/todos
// @access  Private
exports.createTodo = async (req, res, next) => {
  try {
    const todoData = {
      ...req.body,
      beraterId: req.user._id,
      isAutoGenerated: false
    };

    const todo = await Todo.create(todoData);

    const populatedTodo = await Todo.findById(todo._id)
      .populate('relatedCustomerId', 'firstName lastName customerNumber')
      .populate('relatedContractId', 'contractNumber startDate endDate')
      .populate('relatedMeterId', 'meterNumber type');

    res.status(201).json({
      success: true,
      data: populatedTodo
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Update todo
// @route   PUT /api/todos/:id
// @access  Private
exports.updateTodo = async (req, res, next) => {
  try {
    const todo = await Todo.findOne({
      _id: req.params.id,
      beraterId: req.user._id
    });

    if (!todo) {
      return res.status(404).json({
        success: false,
        message: 'TODO nicht gefunden'
      });
    }

    // Erlaubte Felder
    const allowedFields = [
      'title',
      'description',
      'status',
      'priority',
      'dueDate',
      'relatedCustomerId',
      'relatedContractId',
      'relatedMeterId'
    ];

    allowedFields.forEach(field => {
      if (req.body[field] !== undefined) {
        todo[field] = req.body[field];
      }
    });

    await todo.save();

    const populatedTodo = await Todo.findById(todo._id)
      .populate('relatedCustomerId', 'firstName lastName customerNumber')
      .populate('relatedContractId', 'contractNumber startDate endDate')
      .populate('relatedMeterId', 'meterNumber type');

    res.status(200).json({
      success: true,
      data: populatedTodo
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Delete todo
// @route   DELETE /api/todos/:id
// @access  Private
exports.deleteTodo = async (req, res, next) => {
  try {
    const todo = await Todo.findOneAndDelete({
      _id: req.params.id,
      beraterId: req.user._id
    });

    if (!todo) {
      return res.status(404).json({
        success: false,
        message: 'TODO nicht gefunden'
      });
    }

    res.status(200).json({
      success: true,
      message: 'TODO gelöscht'
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Mark todo as completed
// @route   PUT /api/todos/:id/complete
// @access  Private
exports.completeTodo = async (req, res, next) => {
  try {
    const todo = await Todo.findOne({
      _id: req.params.id,
      beraterId: req.user._id
    });

    if (!todo) {
      return res.status(404).json({
        success: false,
        message: 'TODO nicht gefunden'
      });
    }

    todo.status = 'completed';
    await todo.save();

    const populatedTodo = await Todo.findById(todo._id)
      .populate('relatedCustomerId', 'firstName lastName customerNumber')
      .populate('relatedContractId', 'contractNumber startDate endDate')
      .populate('relatedMeterId', 'meterNumber type');

    res.status(200).json({
      success: true,
      data: populatedTodo
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Generate todos for expiring contracts (automatisch)
// @route   POST /api/todos/generate-expiring
// @access  Private (wird als Cron-Job oder manuell aufgerufen)
exports.generateExpiringContractTodos = async (req, res, next) => {
  try {
    const today = new Date();
    const daysAhead = 90;
    const futureDate = new Date(today);
    futureDate.setDate(futureDate.getDate() + daysAhead);

    // Hole Berater-Einstellungen
    const berater = await User.findById(req.user._id);
    const reminderDays = berater?.settings?.reminderDays?.custom || 30;

    // Finde alle Verträge des Beraters die in den nächsten 90 Tagen ablaufen
    const expiringContracts = await Contract.find({
      beraterId: req.user._id,
      endDate: {
        $gte: today,
        $lte: futureDate
      },
      status: 'active'
    }).populate('customerId', 'firstName lastName');

    let createdCount = 0;

    for (const contract of expiringContracts) {
      const daysUntilExpiry = Math.ceil((contract.endDate - today) / (1000 * 60 * 60 * 24));

      // Prüfe ob der Vertrag innerhalb der Erinnerungszeit liegt
      if (daysUntilExpiry > reminderDays) continue;

      // Prüfe ob bereits ein TODO für diesen Vertrag existiert (auch completed)
      const existingTodo = await Todo.findOne({
        beraterId: req.user._id,
        relatedContractId: contract._id,
        autoGenerationType: 'contract_expiring'
      });

      if (existingTodo || !contract.customerId) continue;

      // TODO erstellen
      await Todo.create({
        beraterId: req.user._id,
        title: `Vertrag ${contract.contractNumber} läuft ab`,
        description: `Der Vertrag von ${contract.customerId?.firstName} ${contract.customerId?.lastName} läuft in ${daysUntilExpiry} Tagen ab. Bitte Verlängerung oder Kündigung vorbereiten.`,
        status: 'open',
        priority: daysUntilExpiry <= 30 ? 'high' : daysUntilExpiry <= 60 ? 'medium' : 'low',
        dueDate: contract.endDate,
        relatedCustomerId: contract.customerId,
        relatedContractId: contract._id,
        isAutoGenerated: true,
        autoGenerationType: 'contract_expiring'
      });

      createdCount++;
    }

    res.status(200).json({
      success: true,
      message: `${createdCount} TODO(s) für ablaufende Verträge erstellt`,
      created: createdCount
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Create support ticket (for Berater to report issues to Superadmin)
// @route   POST /api/todos/support-ticket
// @access  Private (Berater only)
exports.createSupportTicket = async (req, res, next) => {
  try {
    const { title, description, priority } = req.body;

    // Validate required fields
    if (!title || !description) {
      return res.status(400).json({
        success: false,
        message: 'Titel und Beschreibung sind erforderlich'
      });
    }

    const ticketData = {
      beraterId: req.user._id,
      title,
      description,
      priority: priority || 'medium',
      status: 'open',
      isSupportTicket: true,
      isAutoGenerated: false,
      ticketImages: [],
      // Initialize conversation with the ticket description as first message
      conversation: [{
        message: description,
        senderType: 'berater',
        senderId: req.user._id,
        senderName: `${req.user.firstName} ${req.user.lastName}`,
        createdAt: new Date()
      }]
    };

    // Handle uploaded images
    if (req.files && req.files.length > 0) {
      ticketData.ticketImages = req.files.map(file => ({
        filename: file.filename,
        originalName: file.originalname,
        path: file.path,
        mimeType: file.mimetype,
        size: file.size
      }));
    }

    const ticket = await Todo.create(ticketData);

    const populatedTicket = await Todo.findById(ticket._id)
      .populate('beraterId', 'firstName lastName email');

    res.status(201).json({
      success: true,
      data: populatedTicket,
      message: 'Support-Ticket erfolgreich erstellt'
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get my support tickets (for Berater - own tickets only)
// @route   GET /api/todos/my-support-tickets
// @access  Private (Berater)
exports.getMySupportTickets = async (req, res, next) => {
  try {
    const { status, priority, page = 1, limit = 50 } = req.query;

    const filter = {
      beraterId: req.user._id,
      isSupportTicket: true
    };

    if (status) filter.status = status;
    if (priority) filter.priority = priority;

    const skip = (page - 1) * limit;
    const total = await Todo.countDocuments(filter);

    const tickets = await Todo.find(filter)
      .populate('respondedBy', 'firstName lastName')
      .sort({ createdAt: -1 })
      .limit(parseInt(limit))
      .skip(skip);

    res.status(200).json({
      success: true,
      data: tickets,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total,
        pages: Math.ceil(total / limit)
      }
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get all support tickets (for Superadmin)
// @route   GET /api/todos/support-tickets
// @access  Private (Superadmin only)
exports.getSupportTickets = async (req, res, next) => {
  try {
    const { status, priority, beraterId, page = 1, limit = 50 } = req.query;

    const filter = { isSupportTicket: true };

    if (status) filter.status = status;
    if (priority) filter.priority = priority;
    if (beraterId) filter.beraterId = beraterId;

    const skip = (page - 1) * limit;
    const total = await Todo.countDocuments(filter);

    const tickets = await Todo.find(filter)
      .populate('beraterId', 'firstName lastName email')
      .populate('respondedBy', 'firstName lastName')
      .sort({ createdAt: -1 })
      .limit(parseInt(limit))
      .skip(skip);

    res.status(200).json({
      success: true,
      data: tickets,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total,
        pages: Math.ceil(total / limit)
      }
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Respond to support ticket / Close ticket
// @route   PUT /api/todos/support-ticket/:id/respond
// @access  Private (Berater can close own tickets, Superadmin can respond and change all statuses)
exports.respondToSupportTicket = async (req, res, next) => {
  try {
    const { response, status } = req.body;

    // At least response or status must be provided
    if (!response && !status) {
      return res.status(400).json({
        success: false,
        message: 'Antwort oder Status ist erforderlich'
      });
    }

    const ticket = await Todo.findOne({
      _id: req.params.id,
      isSupportTicket: true
    });

    if (!ticket) {
      return res.status(404).json({
        success: false,
        message: 'Support-Ticket nicht gefunden'
      });
    }

    const isSuperAdmin = req.user.role === 'superadmin';
    const isTicketOwner = ticket.beraterId.toString() === req.user._id.toString();

    // Check permissions
    if (!isSuperAdmin && !isTicketOwner) {
      return res.status(403).json({
        success: false,
        message: 'Sie können nur Ihre eigenen Tickets verwalten'
      });
    }

    // Berater can change status to open, in_progress, or completed
    if (!isSuperAdmin && status && !['open', 'in_progress', 'completed'].includes(status)) {
      return res.status(403).json({
        success: false,
        message: 'Ungültiger Status'
      });
    }

    // Update response if provided
    if (response && response.trim().length > 0) {
      // Initialize conversation array if needed
      if (!ticket.conversation) {
        ticket.conversation = [];
      }

      // Migrate legacy responses to conversation array if this is the first conversation entry
      if (ticket.conversation.length === 0) {
        // Add existing beraterResponse as first message
        if (ticket.beraterResponse && ticket.beraterResponse.trim().length > 0) {
          ticket.conversation.push({
            message: ticket.beraterResponse.trim(),
            senderType: 'berater',
            senderId: ticket.beraterId,
            senderName: null, // Legacy - name unknown
            createdAt: ticket.beraterResponseAt || ticket.createdAt
          });
        }
        // Add existing adminResponse
        if (ticket.adminResponse && ticket.adminResponse.trim().length > 0) {
          ticket.conversation.push({
            message: ticket.adminResponse.trim(),
            senderType: 'admin',
            senderId: ticket.respondedBy || req.user._id,
            senderName: null, // Legacy - name unknown
            createdAt: ticket.adminResponseAt || ticket.createdAt
          });
        }
      }

      // Add new message to conversation array (chronological)
      const conversationEntry = {
        message: response.trim(),
        senderType: isSuperAdmin ? 'admin' : 'berater',
        senderId: req.user._id,
        senderName: `${req.user.firstName} ${req.user.lastName}`,
        createdAt: new Date()
      };

      ticket.conversation.push(conversationEntry);

      // Also update legacy fields for backward compatibility
      if (isSuperAdmin) {
        // Superadmin response
        ticket.adminResponse = response;
        ticket.adminResponseAt = new Date();
        ticket.respondedBy = req.user._id;
      } else if (isTicketOwner) {
        // Berater can add/update their own response
        ticket.beraterResponse = response;
        ticket.beraterResponseAt = new Date();
      }
    }

    // Update status if provided
    if (status) {
      ticket.status = status;
    }

    await ticket.save();

    const populatedTicket = await Todo.findById(ticket._id)
      .populate('beraterId', 'firstName lastName email')
      .populate('respondedBy', 'firstName lastName');

    res.status(200).json({
      success: true,
      data: populatedTicket,
      message: 'Erfolgreich aktualisiert'
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get unread support ticket count for badge
// @route   GET /api/todos/support-ticket-count
// @access  Private
exports.getSupportTicketBadgeCount = async (req, res, next) => {
  try {
    const isSuperAdmin = req.user.role === 'superadmin';
    let count = 0;

    if (isSuperAdmin) {
      // Superadmin: Zähle offene Tickets ohne Admin-Antwort (noch zu bearbeiten)
      count = await Todo.countDocuments({
        isSupportTicket: true,
        status: { $in: ['open', 'in_progress'] },
        adminResponse: { $in: [null, ''] }
      });
    } else {
      // Berater: Zähle eigene Tickets mit Admin-Antwort, die noch nicht als gelesen markiert wurden
      // (status ist nicht completed und adminResponse existiert)
      count = await Todo.countDocuments({
        beraterId: req.user._id,
        isSupportTicket: true,
        status: { $ne: 'completed' },
        adminResponse: { $nin: [null, ''] },
        adminResponseReadByBerater: { $ne: true }
      });
    }

    res.status(200).json({
      success: true,
      count
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Mark admin response as read by berater
// @route   PUT /api/todos/support-ticket/:id/mark-read
// @access  Private (Berater only)
exports.markSupportTicketAsRead = async (req, res, next) => {
  try {
    const ticket = await Todo.findOne({
      _id: req.params.id,
      beraterId: req.user._id,
      isSupportTicket: true
    });

    if (!ticket) {
      return res.status(404).json({
        success: false,
        message: 'Support-Ticket nicht gefunden'
      });
    }

    ticket.adminResponseReadByBerater = true;
    await ticket.save();

    res.status(200).json({
      success: true,
      message: 'Ticket als gelesen markiert'
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get support ticket image
// @route   GET /api/todos/support-ticket/image/:ticketId/:filename
// @access  Private
exports.getSupportTicketImage = async (req, res, next) => {
  try {
    const { ticketId, filename } = req.params;

    const ticket = await Todo.findById(ticketId);

    if (!ticket || !ticket.isSupportTicket) {
      return res.status(404).send('Support-Ticket nicht gefunden');
    }

    // Check if user has access to this ticket
    if (req.user.role !== 'superadmin' && ticket.beraterId.toString() !== req.user._id.toString()) {
      return res.status(403).send('Keine Berechtigung');
    }

    const image = ticket.ticketImages.find(img => img.filename === filename);

    if (!image) {
      return res.status(404).send('Bild nicht gefunden');
    }

    // Set CORS headers to allow browser to load the image
    res.header('Access-Control-Allow-Origin', req.headers.origin || '*');
    res.header('Access-Control-Allow-Credentials', 'true');
    res.header('Cross-Origin-Resource-Policy', 'cross-origin');

    // Set content type
    res.contentType(image.mimeType);

    // Send the file
    res.sendFile(path.resolve(image.path));
  } catch (error) {
    res.status(500).send('Fehler beim Laden des Bildes');
  }
};

// ============= TODO TOPICS =============

// @desc    Get all topics for current user
// @route   GET /api/todos/topics
// @access  Private
exports.getTopics = async (req, res, next) => {
  try {
    let topics = await TodoTopic.find({ beraterId: req.user._id })
      .sort({ isDefault: -1, name: 1 });

    // Falls keine Topics existieren, erstelle die Standard-Topics
    if (topics.length === 0) {
      const defaultTopics = DEFAULT_TOPICS.map(name => ({
        beraterId: req.user._id,
        name,
        isDefault: true
      }));

      await TodoTopic.insertMany(defaultTopics);
      topics = await TodoTopic.find({ beraterId: req.user._id })
        .sort({ isDefault: -1, name: 1 });
    }

    res.status(200).json({
      success: true,
      data: topics
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Create a new topic
// @route   POST /api/todos/topics
// @access  Private
exports.createTopic = async (req, res, next) => {
  try {
    const { name } = req.body;

    if (!name || !name.trim()) {
      return res.status(400).json({
        success: false,
        message: 'Thema-Name ist erforderlich'
      });
    }

    // Prüfe ob das Thema bereits existiert
    const existingTopic = await TodoTopic.findOne({
      beraterId: req.user._id,
      name: name.trim()
    });

    if (existingTopic) {
      return res.status(400).json({
        success: false,
        message: 'Dieses Thema existiert bereits'
      });
    }

    const topic = await TodoTopic.create({
      beraterId: req.user._id,
      name: name.trim(),
      isDefault: false
    });

    res.status(201).json({
      success: true,
      data: topic
    });
  } catch (error) {
    if (error.code === 11000) {
      return res.status(400).json({
        success: false,
        message: 'Dieses Thema existiert bereits'
      });
    }
    next(error);
  }
};

// @desc    Delete a topic
// @route   DELETE /api/todos/topics/:id
// @access  Private
exports.deleteTopic = async (req, res, next) => {
  try {
    const topic = await TodoTopic.findOne({
      _id: req.params.id,
      beraterId: req.user._id
    });

    if (!topic) {
      return res.status(404).json({
        success: false,
        message: 'Thema nicht gefunden'
      });
    }

    // Standard-Themen können nicht gelöscht werden
    if (topic.isDefault) {
      return res.status(400).json({
        success: false,
        message: 'Standard-Themen können nicht gelöscht werden'
      });
    }

    await TodoTopic.deleteOne({ _id: topic._id });

    res.status(200).json({
      success: true,
      message: 'Thema gelöscht'
    });
  } catch (error) {
    next(error);
  }
};
