const Todo = require('../models/Todo');
const Contract = require('../models/Contract');
const Reminder = require('../models/Reminder');
const path = require('path');
const fs = require('fs').promises;

// @desc    Get all todos (including reminders converted to TODOs)
// @route   GET /api/todos
// @access  Private
exports.getTodos = async (req, res, next) => {
  try {
    const { status, priority, search, page = 1, limit = 50 } = req.query;

    const filter = { beraterId: req.user._id, isSupportTicket: { $ne: true } };

    if (status) filter.status = status;
    if (priority) filter.priority = priority;
    if (search) {
      filter.$or = [
        { title: { $regex: search, $options: 'i' } },
        { description: { $regex: search, $options: 'i' } }
      ];
    }

    // Fetch regular TODOs
    const todos = await Todo.find(filter)
      .populate('relatedCustomerId', 'firstName lastName customerNumber')
      .populate('relatedContractId', 'contractNumber startDate endDate')
      .populate('relatedMeterId', 'meterNumber type')
      .lean();

    // Fetch Reminders and convert them to TODO format
    const reminderFilter = { beraterId: req.user._id };

    // Map status filter to reminder status
    if (status) {
      if (status === 'completed') {
        reminderFilter.status = 'done';
      } else if (status === 'open' || status === 'in_progress') {
        reminderFilter.status = 'open';
      }
    }

    const reminders = await Reminder.find(reminderFilter)
      .populate({
        path: 'contractId',
        populate: [
          { path: 'customerId', select: 'firstName lastName customerNumber' },
          { path: 'supplierId', select: 'name shortName' }
        ]
      })
      .lean();

    // Convert reminders to TODO format
    const reminderTodos = reminders.map(reminder => {
      const daysMap = {
        '30days': 30,
        '60days': 60,
        '90days': 90
      };
      const days = daysMap[reminder.reminderType] || 90;

      const priorityMap = {
        '30days': 'high',
        '60days': 'medium',
        '90days': 'low'
      };
      const reminderPriority = priorityMap[reminder.reminderType] || 'low';

      // Skip if priority filter doesn't match
      if (priority && reminderPriority !== priority) {
        return null;
      }

      const statusMap = {
        'open': 'open',
        'done': 'completed',
        'ignored': 'completed'
      };

      const title = `Vertrag läuft in ${days} Tagen ab`;
      const customerName = reminder.contractId?.customerId
        ? `${reminder.contractId.customerId.firstName} ${reminder.contractId.customerId.lastName}`
        : 'Unbekannt';
      const supplierName = reminder.contractId?.supplierId?.name || 'Unbekannt';

      const description = `Erinnerung: Der Vertrag von ${customerName} bei ${supplierName} läuft bald ab. Bitte rechtzeitig Verlängerung oder Kündigung vorbereiten.`;

      // Apply search filter
      if (search) {
        const searchLower = search.toLowerCase();
        if (!title.toLowerCase().includes(searchLower) &&
            !description.toLowerCase().includes(searchLower)) {
          return null;
        }
      }

      return {
        _id: `reminder_${reminder._id}`,
        title,
        description,
        status: statusMap[reminder.status] || 'open',
        priority: reminderPriority,
        dueDate: reminder.dueDate,
        relatedCustomerId: reminder.contractId?.customerId || null,
        relatedContractId: reminder.contractId || null,
        relatedMeterId: null,
        isAutoGenerated: true,
        autoGenerationType: 'reminder_due',
        isReminder: true,
        originalReminderId: reminder._id,
        note: reminder.note,
        createdAt: reminder.createdAt,
        updatedAt: reminder.updatedAt,
        beraterId: reminder.beraterId
      };
    }).filter(Boolean); // Remove null entries from filtering

    // Combine both arrays
    const allTodos = [...todos, ...reminderTodos];

    // Sort by dueDate, then createdAt
    allTodos.sort((a, b) => {
      if (a.dueDate && b.dueDate) {
        return new Date(a.dueDate) - new Date(b.dueDate);
      }
      if (a.dueDate) return -1;
      if (b.dueDate) return 1;
      return new Date(b.createdAt) - new Date(a.createdAt);
    });

    // Apply pagination to combined results
    const skip = (page - 1) * limit;
    const total = allTodos.length;
    const paginatedTodos = allTodos.slice(skip, skip + parseInt(limit));

    res.status(200).json({
      success: true,
      data: paginatedTodos,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total,
        pages: Math.ceil(total / limit)
      }
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get single todo
// @route   GET /api/todos/:id
// @access  Private
exports.getTodo = async (req, res, next) => {
  try {
    const todo = await Todo.findOne({
      _id: req.params.id,
      beraterId: req.user._id
    })
      .populate('relatedCustomerId', 'firstName lastName customerNumber')
      .populate('relatedContractId', 'contractNumber startDate endDate')
      .populate('relatedMeterId', 'meterNumber type');

    if (!todo) {
      return res.status(404).json({
        success: false,
        message: 'TODO nicht gefunden'
      });
    }

    res.status(200).json({
      success: true,
      data: todo
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Create todo
// @route   POST /api/todos
// @access  Private
exports.createTodo = async (req, res, next) => {
  try {
    const todoData = {
      ...req.body,
      beraterId: req.user._id,
      isAutoGenerated: false
    };

    const todo = await Todo.create(todoData);

    // Wenn ein TODO für einen Vertrag erstellt wird, lösche existierende offene Reminders
    // um Duplikate zu vermeiden
    if (todo.relatedContractId) {
      await Reminder.updateMany(
        {
          beraterId: req.user._id,
          contractId: todo.relatedContractId,
          status: 'open'
        },
        {
          status: 'ignored',
          note: 'Automatisch ignoriert - Manuelles TODO wurde erstellt'
        }
      );
    }

    const populatedTodo = await Todo.findById(todo._id)
      .populate('relatedCustomerId', 'firstName lastName customerNumber')
      .populate('relatedContractId', 'contractNumber startDate endDate')
      .populate('relatedMeterId', 'meterNumber type');

    res.status(201).json({
      success: true,
      data: populatedTodo
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Update todo (or reminder-based todo)
// @route   PUT /api/todos/:id
// @access  Private
exports.updateTodo = async (req, res, next) => {
  try {
    // Check if this is a reminder-based TODO
    if (req.params.id.startsWith('reminder_')) {
      const reminderId = req.params.id.replace('reminder_', '');

      const reminder = await Reminder.findOne({
        _id: reminderId,
        beraterId: req.user._id
      });

      if (!reminder) {
        return res.status(404).json({
          success: false,
          message: 'Erinnerung nicht gefunden'
        });
      }

      // Update reminder status based on TODO status
      if (req.body.status) {
        const statusMap = {
          'open': 'open',
          'in_progress': 'open',
          'completed': 'done'
        };
        reminder.status = statusMap[req.body.status] || 'open';
      }

      // Update note if provided
      if (req.body.note !== undefined) {
        reminder.note = req.body.note;
      }

      await reminder.save();

      // Return the reminder as a TODO
      const populatedReminder = await Reminder.findById(reminder._id)
        .populate({
          path: 'contractId',
          populate: [
            { path: 'customerId', select: 'firstName lastName customerNumber' },
            { path: 'supplierId', select: 'name shortName' }
          ]
        });

      const daysMap = {
        '30days': 30,
        '60days': 60,
        '90days': 90
      };
      const days = daysMap[populatedReminder.reminderType] || 90;

      const priorityMap = {
        '30days': 'high',
        '60days': 'medium',
        '90days': 'low'
      };

      const statusMap = {
        'open': 'open',
        'done': 'completed',
        'ignored': 'completed'
      };

      const customerName = populatedReminder.contractId?.customerId
        ? `${populatedReminder.contractId.customerId.firstName} ${populatedReminder.contractId.customerId.lastName}`
        : 'Unbekannt';
      const supplierName = populatedReminder.contractId?.supplierId?.name || 'Unbekannt';

      const reminderTodo = {
        _id: `reminder_${populatedReminder._id}`,
        title: `Vertrag läuft in ${days} Tagen ab`,
        description: `Erinnerung: Der Vertrag von ${customerName} bei ${supplierName} läuft bald ab. Bitte rechtzeitig Verlängerung oder Kündigung vorbereiten.`,
        status: statusMap[populatedReminder.status] || 'open',
        priority: priorityMap[populatedReminder.reminderType] || 'low',
        dueDate: populatedReminder.dueDate,
        relatedCustomerId: populatedReminder.contractId?.customerId || null,
        relatedContractId: populatedReminder.contractId || null,
        relatedMeterId: null,
        isAutoGenerated: true,
        autoGenerationType: 'reminder_due',
        isReminder: true,
        originalReminderId: populatedReminder._id,
        note: populatedReminder.note,
        createdAt: populatedReminder.createdAt,
        updatedAt: populatedReminder.updatedAt,
        beraterId: populatedReminder.beraterId
      };

      return res.status(200).json({
        success: true,
        data: reminderTodo
      });
    }

    // Regular TODO update
    const todo = await Todo.findOne({
      _id: req.params.id,
      beraterId: req.user._id
    });

    if (!todo) {
      return res.status(404).json({
        success: false,
        message: 'TODO nicht gefunden'
      });
    }

    // Erlaubte Felder
    const allowedFields = [
      'title',
      'description',
      'status',
      'priority',
      'dueDate',
      'relatedCustomerId',
      'relatedContractId',
      'relatedMeterId'
    ];

    allowedFields.forEach(field => {
      if (req.body[field] !== undefined) {
        todo[field] = req.body[field];
      }
    });

    await todo.save();

    const populatedTodo = await Todo.findById(todo._id)
      .populate('relatedCustomerId', 'firstName lastName customerNumber')
      .populate('relatedContractId', 'contractNumber startDate endDate')
      .populate('relatedMeterId', 'meterNumber type');

    res.status(200).json({
      success: true,
      data: populatedTodo
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Delete todo (or reminder-based todo)
// @route   DELETE /api/todos/:id
// @access  Private
exports.deleteTodo = async (req, res, next) => {
  try {
    // Check if this is a reminder-based TODO
    if (req.params.id.startsWith('reminder_')) {
      const reminderId = req.params.id.replace('reminder_', '');

      const reminder = await Reminder.findOne({
        _id: reminderId,
        beraterId: req.user._id
      });

      if (!reminder) {
        return res.status(404).json({
          success: false,
          message: 'Erinnerung nicht gefunden'
        });
      }

      // Mark reminder as ignored instead of deleting
      reminder.status = 'ignored';
      await reminder.save();

      return res.status(200).json({
        success: true,
        message: 'Erinnerung ignoriert'
      });
    }

    // Regular TODO delete
    const todo = await Todo.findOneAndDelete({
      _id: req.params.id,
      beraterId: req.user._id
    });

    if (!todo) {
      return res.status(404).json({
        success: false,
        message: 'TODO nicht gefunden'
      });
    }

    res.status(200).json({
      success: true,
      message: 'TODO gelöscht'
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Mark todo as completed (or reminder-based todo)
// @route   PUT /api/todos/:id/complete
// @access  Private
exports.completeTodo = async (req, res, next) => {
  try {
    // Check if this is a reminder-based TODO
    if (req.params.id.startsWith('reminder_')) {
      const reminderId = req.params.id.replace('reminder_', '');

      const reminder = await Reminder.findOne({
        _id: reminderId,
        beraterId: req.user._id
      });

      if (!reminder) {
        return res.status(404).json({
          success: false,
          message: 'Erinnerung nicht gefunden'
        });
      }

      reminder.status = 'done';
      await reminder.save();

      // Return the reminder as a TODO
      const populatedReminder = await Reminder.findById(reminder._id)
        .populate({
          path: 'contractId',
          populate: [
            { path: 'customerId', select: 'firstName lastName customerNumber' },
            { path: 'supplierId', select: 'name shortName' }
          ]
        });

      const daysMap = {
        '30days': 30,
        '60days': 60,
        '90days': 90
      };
      const days = daysMap[populatedReminder.reminderType] || 90;

      const priorityMap = {
        '30days': 'high',
        '60days': 'medium',
        '90days': 'low'
      };

      const customerName = populatedReminder.contractId?.customerId
        ? `${populatedReminder.contractId.customerId.firstName} ${populatedReminder.contractId.customerId.lastName}`
        : 'Unbekannt';
      const supplierName = populatedReminder.contractId?.supplierId?.name || 'Unbekannt';

      const reminderTodo = {
        _id: `reminder_${populatedReminder._id}`,
        title: `Vertrag läuft in ${days} Tagen ab`,
        description: `Erinnerung: Der Vertrag von ${customerName} bei ${supplierName} läuft bald ab. Bitte rechtzeitig Verlängerung oder Kündigung vorbereiten.`,
        status: 'completed',
        priority: priorityMap[populatedReminder.reminderType] || 'low',
        dueDate: populatedReminder.dueDate,
        relatedCustomerId: populatedReminder.contractId?.customerId || null,
        relatedContractId: populatedReminder.contractId || null,
        relatedMeterId: null,
        isAutoGenerated: true,
        autoGenerationType: 'reminder_due',
        isReminder: true,
        originalReminderId: populatedReminder._id,
        note: populatedReminder.note,
        createdAt: populatedReminder.createdAt,
        updatedAt: populatedReminder.updatedAt,
        beraterId: populatedReminder.beraterId
      };

      return res.status(200).json({
        success: true,
        data: reminderTodo
      });
    }

    // Regular TODO complete
    const todo = await Todo.findOne({
      _id: req.params.id,
      beraterId: req.user._id
    });

    if (!todo) {
      return res.status(404).json({
        success: false,
        message: 'TODO nicht gefunden'
      });
    }

    todo.status = 'completed';
    await todo.save();

    const populatedTodo = await Todo.findById(todo._id)
      .populate('relatedCustomerId', 'firstName lastName customerNumber')
      .populate('relatedContractId', 'contractNumber startDate endDate')
      .populate('relatedMeterId', 'meterNumber type');

    res.status(200).json({
      success: true,
      data: populatedTodo
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Generate todos for expiring contracts (automatisch)
// @route   POST /api/todos/generate-expiring
// @access  Private (wird als Cron-Job oder manuell aufgerufen)
exports.generateExpiringContractTodos = async (req, res, next) => {
  try {
    const today = new Date();
    const daysAhead = 90; // 90 Tage im Voraus
    const futureDate = new Date(today);
    futureDate.setDate(futureDate.getDate() + daysAhead);

    // Finde alle Verträge die in den nächsten 90 Tagen ablaufen
    const expiringContracts = await Contract.find({
      endDate: {
        $gte: today,
        $lte: futureDate
      },
      status: 'active'
    }).populate('customerId', 'firstName lastName');

    let createdCount = 0;

    for (const contract of expiringContracts) {
      // Prüfe ob bereits ein TODO für diesen Vertrag existiert
      const existingTodo = await Todo.findOne({
        beraterId: contract.beraterId,
        relatedContractId: contract._id,
        autoGenerationType: 'contract_expiring',
        status: { $ne: 'completed' }
      });

      // Prüfe auch ob bereits ein Reminder für diesen Vertrag existiert
      const existingReminder = await Reminder.findOne({
        beraterId: contract.beraterId,
        contractId: contract._id,
        status: { $ne: 'done' }
      });

      // Nur erstellen wenn weder TODO noch Reminder existiert
      if (!existingTodo && !existingReminder) {
        const daysUntilExpiry = Math.ceil((contract.endDate - today) / (1000 * 60 * 60 * 24));

        await Todo.create({
          beraterId: contract.beraterId,
          title: `Vertrag ${contract.contractNumber} läuft ab`,
          description: `Der Vertrag von ${contract.customerId?.firstName} ${contract.customerId?.lastName} läuft in ${daysUntilExpiry} Tagen ab. Bitte Verlängerung oder Kündigung vorbereiten.`,
          status: 'open',
          priority: daysUntilExpiry <= 30 ? 'high' : daysUntilExpiry <= 60 ? 'medium' : 'low',
          dueDate: contract.endDate,
          relatedCustomerId: contract.customerId,
          relatedContractId: contract._id,
          isAutoGenerated: true,
          autoGenerationType: 'contract_expiring'
        });

        createdCount++;
      }
    }

    res.status(200).json({
      success: true,
      message: `${createdCount} TODO(s) für ablaufende Verträge erstellt`,
      created: createdCount
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Create support ticket (for Berater to report issues to Superadmin)
// @route   POST /api/todos/support-ticket
// @access  Private (Berater only)
exports.createSupportTicket = async (req, res, next) => {
  try {
    const { title, description, priority } = req.body;

    // Validate required fields
    if (!title || !description) {
      return res.status(400).json({
        success: false,
        message: 'Titel und Beschreibung sind erforderlich'
      });
    }

    const ticketData = {
      beraterId: req.user._id,
      title,
      description,
      priority: priority || 'medium',
      status: 'open',
      isSupportTicket: true,
      isAutoGenerated: false,
      ticketImages: []
    };

    // Handle uploaded images
    if (req.files && req.files.length > 0) {
      ticketData.ticketImages = req.files.map(file => ({
        filename: file.filename,
        originalName: file.originalname,
        path: file.path,
        mimeType: file.mimetype,
        size: file.size
      }));
    }

    const ticket = await Todo.create(ticketData);

    const populatedTicket = await Todo.findById(ticket._id)
      .populate('beraterId', 'firstName lastName email');

    res.status(201).json({
      success: true,
      data: populatedTicket,
      message: 'Support-Ticket erfolgreich erstellt'
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get my support tickets (for Berater - own tickets only)
// @route   GET /api/todos/my-support-tickets
// @access  Private (Berater)
exports.getMySupportTickets = async (req, res, next) => {
  try {
    const { status, priority, page = 1, limit = 50 } = req.query;

    const filter = {
      beraterId: req.user._id,
      isSupportTicket: true
    };

    if (status) filter.status = status;
    if (priority) filter.priority = priority;

    const skip = (page - 1) * limit;
    const total = await Todo.countDocuments(filter);

    const tickets = await Todo.find(filter)
      .populate('respondedBy', 'firstName lastName')
      .sort({ createdAt: -1 })
      .limit(parseInt(limit))
      .skip(skip);

    res.status(200).json({
      success: true,
      data: tickets,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total,
        pages: Math.ceil(total / limit)
      }
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get all support tickets (for Superadmin)
// @route   GET /api/todos/support-tickets
// @access  Private (Superadmin only)
exports.getSupportTickets = async (req, res, next) => {
  try {
    const { status, priority, beraterId, page = 1, limit = 50 } = req.query;

    const filter = { isSupportTicket: true };

    if (status) filter.status = status;
    if (priority) filter.priority = priority;
    if (beraterId) filter.beraterId = beraterId;

    const skip = (page - 1) * limit;
    const total = await Todo.countDocuments(filter);

    const tickets = await Todo.find(filter)
      .populate('beraterId', 'firstName lastName email')
      .populate('respondedBy', 'firstName lastName')
      .sort({ createdAt: -1 })
      .limit(parseInt(limit))
      .skip(skip);

    res.status(200).json({
      success: true,
      data: tickets,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total,
        pages: Math.ceil(total / limit)
      }
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Respond to support ticket / Close ticket
// @route   PUT /api/todos/support-ticket/:id/respond
// @access  Private (Berater can close own tickets, Superadmin can respond and change all statuses)
exports.respondToSupportTicket = async (req, res, next) => {
  try {
    const { response, status } = req.body;

    // At least response or status must be provided
    if (!response && !status) {
      return res.status(400).json({
        success: false,
        message: 'Antwort oder Status ist erforderlich'
      });
    }

    const ticket = await Todo.findOne({
      _id: req.params.id,
      isSupportTicket: true
    });

    if (!ticket) {
      return res.status(404).json({
        success: false,
        message: 'Support-Ticket nicht gefunden'
      });
    }

    const isSuperAdmin = req.user.role === 'superadmin';
    const isTicketOwner = ticket.beraterId.toString() === req.user._id.toString();

    // Check permissions
    if (!isSuperAdmin && !isTicketOwner) {
      return res.status(403).json({
        success: false,
        message: 'Sie können nur Ihre eigenen Tickets verwalten'
      });
    }

    // Berater can change status to open, in_progress, or completed
    if (!isSuperAdmin && status && !['open', 'in_progress', 'completed'].includes(status)) {
      return res.status(403).json({
        success: false,
        message: 'Ungültiger Status'
      });
    }

    // Update response if provided
    if (response && response.trim().length > 0) {
      if (isSuperAdmin) {
        // Superadmin response
        ticket.adminResponse = response;
        ticket.adminResponseAt = new Date();
        ticket.respondedBy = req.user._id;
      } else if (isTicketOwner) {
        // Berater can add/update their own response
        ticket.beraterResponse = response;
        ticket.beraterResponseAt = new Date();
      }
    }

    // Update status if provided
    if (status) {
      ticket.status = status;
    }

    await ticket.save();

    const populatedTicket = await Todo.findById(ticket._id)
      .populate('beraterId', 'firstName lastName email')
      .populate('respondedBy', 'firstName lastName');

    res.status(200).json({
      success: true,
      data: populatedTicket,
      message: 'Erfolgreich aktualisiert'
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get unread support ticket count for badge
// @route   GET /api/todos/support-ticket-count
// @access  Private
exports.getSupportTicketBadgeCount = async (req, res, next) => {
  try {
    const isSuperAdmin = req.user.role === 'superadmin';
    let count = 0;

    if (isSuperAdmin) {
      // Superadmin: Zähle offene Tickets ohne Admin-Antwort (noch zu bearbeiten)
      count = await Todo.countDocuments({
        isSupportTicket: true,
        status: { $in: ['open', 'in_progress'] },
        adminResponse: { $in: [null, ''] }
      });
    } else {
      // Berater: Zähle eigene Tickets mit Admin-Antwort, die noch nicht als gelesen markiert wurden
      // (status ist nicht completed und adminResponse existiert)
      count = await Todo.countDocuments({
        beraterId: req.user._id,
        isSupportTicket: true,
        status: { $ne: 'completed' },
        adminResponse: { $nin: [null, ''] },
        adminResponseReadByBerater: { $ne: true }
      });
    }

    res.status(200).json({
      success: true,
      count
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Mark admin response as read by berater
// @route   PUT /api/todos/support-ticket/:id/mark-read
// @access  Private (Berater only)
exports.markSupportTicketAsRead = async (req, res, next) => {
  try {
    const ticket = await Todo.findOne({
      _id: req.params.id,
      beraterId: req.user._id,
      isSupportTicket: true
    });

    if (!ticket) {
      return res.status(404).json({
        success: false,
        message: 'Support-Ticket nicht gefunden'
      });
    }

    ticket.adminResponseReadByBerater = true;
    await ticket.save();

    res.status(200).json({
      success: true,
      message: 'Ticket als gelesen markiert'
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get support ticket image
// @route   GET /api/todos/support-ticket/image/:ticketId/:filename
// @access  Private
exports.getSupportTicketImage = async (req, res, next) => {
  try {
    const { ticketId, filename } = req.params;

    const ticket = await Todo.findById(ticketId);

    if (!ticket || !ticket.isSupportTicket) {
      return res.status(404).send('Support-Ticket nicht gefunden');
    }

    // Check if user has access to this ticket
    if (req.user.role !== 'superadmin' && ticket.beraterId.toString() !== req.user._id.toString()) {
      return res.status(403).send('Keine Berechtigung');
    }

    const image = ticket.ticketImages.find(img => img.filename === filename);

    if (!image) {
      return res.status(404).send('Bild nicht gefunden');
    }

    // Set CORS headers to allow browser to load the image
    res.header('Access-Control-Allow-Origin', req.headers.origin || '*');
    res.header('Access-Control-Allow-Credentials', 'true');
    res.header('Cross-Origin-Resource-Policy', 'cross-origin');

    // Set content type
    res.contentType(image.mimeType);

    // Send the file
    res.sendFile(path.resolve(image.path));
  } catch (error) {
    res.status(500).send('Fehler beim Laden des Bildes');
  }
};
