const Todo = require('../models/Todo');
const Contract = require('../models/Contract');
const path = require('path');
const fs = require('fs').promises;

// @desc    Get all todos
// @route   GET /api/todos
// @access  Private
exports.getTodos = async (req, res, next) => {
  try {
    const { status, priority, search, page = 1, limit = 50 } = req.query;

    const filter = { beraterId: req.user._id, isSupportTicket: { $ne: true } };

    if (status) filter.status = status;
    if (priority) filter.priority = priority;
    if (search) {
      filter.$or = [
        { title: { $regex: search, $options: 'i' } },
        { description: { $regex: search, $options: 'i' } }
      ];
    }

    const skip = (page - 1) * limit;
    const total = await Todo.countDocuments(filter);

    const todos = await Todo.find(filter)
      .populate('relatedCustomerId', 'firstName lastName customerNumber')
      .populate('relatedContractId', 'contractNumber startDate endDate')
      .populate('relatedMeterId', 'meterNumber type')
      .sort({ dueDate: 1, createdAt: -1 })
      .limit(parseInt(limit))
      .skip(skip);

    res.status(200).json({
      success: true,
      data: todos,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total,
        pages: Math.ceil(total / limit)
      }
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get single todo
// @route   GET /api/todos/:id
// @access  Private
exports.getTodo = async (req, res, next) => {
  try {
    const todo = await Todo.findOne({
      _id: req.params.id,
      beraterId: req.user._id
    })
      .populate('relatedCustomerId', 'firstName lastName customerNumber')
      .populate('relatedContractId', 'contractNumber startDate endDate')
      .populate('relatedMeterId', 'meterNumber type');

    if (!todo) {
      return res.status(404).json({
        success: false,
        message: 'TODO nicht gefunden'
      });
    }

    res.status(200).json({
      success: true,
      data: todo
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Create todo
// @route   POST /api/todos
// @access  Private
exports.createTodo = async (req, res, next) => {
  try {
    const todoData = {
      ...req.body,
      beraterId: req.user._id,
      isAutoGenerated: false
    };

    const todo = await Todo.create(todoData);

    const populatedTodo = await Todo.findById(todo._id)
      .populate('relatedCustomerId', 'firstName lastName customerNumber')
      .populate('relatedContractId', 'contractNumber startDate endDate')
      .populate('relatedMeterId', 'meterNumber type');

    res.status(201).json({
      success: true,
      data: populatedTodo
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Update todo
// @route   PUT /api/todos/:id
// @access  Private
exports.updateTodo = async (req, res, next) => {
  try {
    const todo = await Todo.findOne({
      _id: req.params.id,
      beraterId: req.user._id
    });

    if (!todo) {
      return res.status(404).json({
        success: false,
        message: 'TODO nicht gefunden'
      });
    }

    // Erlaubte Felder
    const allowedFields = [
      'title',
      'description',
      'status',
      'priority',
      'dueDate',
      'relatedCustomerId',
      'relatedContractId',
      'relatedMeterId'
    ];

    allowedFields.forEach(field => {
      if (req.body[field] !== undefined) {
        todo[field] = req.body[field];
      }
    });

    await todo.save();

    const populatedTodo = await Todo.findById(todo._id)
      .populate('relatedCustomerId', 'firstName lastName customerNumber')
      .populate('relatedContractId', 'contractNumber startDate endDate')
      .populate('relatedMeterId', 'meterNumber type');

    res.status(200).json({
      success: true,
      data: populatedTodo
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Delete todo
// @route   DELETE /api/todos/:id
// @access  Private
exports.deleteTodo = async (req, res, next) => {
  try {
    const todo = await Todo.findOneAndDelete({
      _id: req.params.id,
      beraterId: req.user._id
    });

    if (!todo) {
      return res.status(404).json({
        success: false,
        message: 'TODO nicht gefunden'
      });
    }

    res.status(200).json({
      success: true,
      message: 'TODO gelöscht'
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Mark todo as completed
// @route   PUT /api/todos/:id/complete
// @access  Private
exports.completeTodo = async (req, res, next) => {
  try {
    const todo = await Todo.findOne({
      _id: req.params.id,
      beraterId: req.user._id
    });

    if (!todo) {
      return res.status(404).json({
        success: false,
        message: 'TODO nicht gefunden'
      });
    }

    todo.status = 'completed';
    await todo.save();

    const populatedTodo = await Todo.findById(todo._id)
      .populate('relatedCustomerId', 'firstName lastName customerNumber')
      .populate('relatedContractId', 'contractNumber startDate endDate')
      .populate('relatedMeterId', 'meterNumber type');

    res.status(200).json({
      success: true,
      data: populatedTodo
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Generate todos for expiring contracts (automatisch)
// @route   POST /api/todos/generate-expiring
// @access  Private (wird als Cron-Job oder manuell aufgerufen)
exports.generateExpiringContractTodos = async (req, res, next) => {
  try {
    const today = new Date();
    const daysAhead = 90; // 90 Tage im Voraus
    const futureDate = new Date(today);
    futureDate.setDate(futureDate.getDate() + daysAhead);

    // Finde alle Verträge die in den nächsten 90 Tagen ablaufen
    const expiringContracts = await Contract.find({
      endDate: {
        $gte: today,
        $lte: futureDate
      },
      status: 'active'
    }).populate('customerId', 'firstName lastName');

    let createdCount = 0;

    for (const contract of expiringContracts) {
      // Prüfe ob bereits ein TODO für diesen Vertrag existiert
      const existingTodo = await Todo.findOne({
        beraterId: contract.beraterId,
        relatedContractId: contract._id,
        autoGenerationType: 'contract_expiring',
        status: { $ne: 'completed' }
      });

      if (!existingTodo) {
        const daysUntilExpiry = Math.ceil((contract.endDate - today) / (1000 * 60 * 60 * 24));

        await Todo.create({
          beraterId: contract.beraterId,
          title: `Vertrag ${contract.contractNumber} läuft ab`,
          description: `Der Vertrag von ${contract.customerId?.firstName} ${contract.customerId?.lastName} läuft in ${daysUntilExpiry} Tagen ab. Bitte Verlängerung oder Kündigung vorbereiten.`,
          status: 'open',
          priority: daysUntilExpiry <= 30 ? 'high' : daysUntilExpiry <= 60 ? 'medium' : 'low',
          dueDate: contract.endDate,
          relatedCustomerId: contract.customerId,
          relatedContractId: contract._id,
          isAutoGenerated: true,
          autoGenerationType: 'contract_expiring'
        });

        createdCount++;
      }
    }

    res.status(200).json({
      success: true,
      message: `${createdCount} TODO(s) für ablaufende Verträge erstellt`,
      created: createdCount
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Create support ticket (for Berater to report issues to Superadmin)
// @route   POST /api/todos/support-ticket
// @access  Private (Berater only)
exports.createSupportTicket = async (req, res, next) => {
  try {
    const { title, description, priority } = req.body;

    // Validate required fields
    if (!title || !description) {
      return res.status(400).json({
        success: false,
        message: 'Titel und Beschreibung sind erforderlich'
      });
    }

    const ticketData = {
      beraterId: req.user._id,
      title,
      description,
      priority: priority || 'medium',
      status: 'open',
      isSupportTicket: true,
      isAutoGenerated: false,
      ticketImages: []
    };

    // Handle uploaded images
    if (req.files && req.files.length > 0) {
      ticketData.ticketImages = req.files.map(file => ({
        filename: file.filename,
        originalName: file.originalname,
        path: file.path,
        mimeType: file.mimetype,
        size: file.size
      }));
    }

    const ticket = await Todo.create(ticketData);

    const populatedTicket = await Todo.findById(ticket._id)
      .populate('beraterId', 'firstName lastName email');

    res.status(201).json({
      success: true,
      data: populatedTicket,
      message: 'Support-Ticket erfolgreich erstellt'
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get my support tickets (for Berater - own tickets only)
// @route   GET /api/todos/my-support-tickets
// @access  Private (Berater)
exports.getMySupportTickets = async (req, res, next) => {
  try {
    const { status, priority, page = 1, limit = 50 } = req.query;

    const filter = {
      beraterId: req.user._id,
      isSupportTicket: true
    };

    if (status) filter.status = status;
    if (priority) filter.priority = priority;

    const skip = (page - 1) * limit;
    const total = await Todo.countDocuments(filter);

    const tickets = await Todo.find(filter)
      .populate('respondedBy', 'firstName lastName')
      .sort({ createdAt: -1 })
      .limit(parseInt(limit))
      .skip(skip);

    res.status(200).json({
      success: true,
      data: tickets,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total,
        pages: Math.ceil(total / limit)
      }
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get all support tickets (for Superadmin)
// @route   GET /api/todos/support-tickets
// @access  Private (Superadmin only)
exports.getSupportTickets = async (req, res, next) => {
  try {
    const { status, priority, beraterId, page = 1, limit = 50 } = req.query;

    const filter = { isSupportTicket: true };

    if (status) filter.status = status;
    if (priority) filter.priority = priority;
    if (beraterId) filter.beraterId = beraterId;

    const skip = (page - 1) * limit;
    const total = await Todo.countDocuments(filter);

    const tickets = await Todo.find(filter)
      .populate('beraterId', 'firstName lastName email')
      .populate('respondedBy', 'firstName lastName')
      .sort({ createdAt: -1 })
      .limit(parseInt(limit))
      .skip(skip);

    res.status(200).json({
      success: true,
      data: tickets,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total,
        pages: Math.ceil(total / limit)
      }
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Respond to support ticket (for Superadmin)
// @route   PUT /api/todos/support-ticket/:id/respond
// @access  Private (Superadmin only)
exports.respondToSupportTicket = async (req, res, next) => {
  try {
    const { response, status } = req.body;

    // At least response or status must be provided
    if (!response && !status) {
      return res.status(400).json({
        success: false,
        message: 'Antwort oder Status ist erforderlich'
      });
    }

    const ticket = await Todo.findOne({
      _id: req.params.id,
      isSupportTicket: true
    });

    if (!ticket) {
      return res.status(404).json({
        success: false,
        message: 'Support-Ticket nicht gefunden'
      });
    }

    // Update response if provided
    if (response && response.trim().length > 0) {
      ticket.adminResponse = response;
      ticket.adminResponseAt = new Date();
      ticket.respondedBy = req.user._id;
    }

    // Update status if provided
    if (status) {
      ticket.status = status;
    }

    await ticket.save();

    const populatedTicket = await Todo.findById(ticket._id)
      .populate('beraterId', 'firstName lastName email')
      .populate('respondedBy', 'firstName lastName');

    res.status(200).json({
      success: true,
      data: populatedTicket,
      message: 'Erfolgreich aktualisiert'
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get support ticket image
// @route   GET /api/todos/support-ticket/image/:ticketId/:filename
// @access  Private
exports.getSupportTicketImage = async (req, res, next) => {
  try {
    const { ticketId, filename } = req.params;

    const ticket = await Todo.findById(ticketId);

    if (!ticket || !ticket.isSupportTicket) {
      return res.status(404).send('Support-Ticket nicht gefunden');
    }

    // Check if user has access to this ticket
    if (req.user.role !== 'superadmin' && ticket.beraterId.toString() !== req.user._id.toString()) {
      return res.status(403).send('Keine Berechtigung');
    }

    const image = ticket.ticketImages.find(img => img.filename === filename);

    if (!image) {
      return res.status(404).send('Bild nicht gefunden');
    }

    // Set CORS headers to allow browser to load the image
    res.header('Access-Control-Allow-Origin', req.headers.origin || '*');
    res.header('Access-Control-Allow-Credentials', 'true');
    res.header('Cross-Origin-Resource-Policy', 'cross-origin');

    // Set content type
    res.contentType(image.mimeType);

    // Send the file
    res.sendFile(path.resolve(image.path));
  } catch (error) {
    res.status(500).send('Fehler beim Laden des Bildes');
  }
};
