import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '../../environments/environment';

export interface Todo {
  _id: string;
  beraterId: string | {
    _id: string;
    firstName: string;
    lastName: string;
    email: string;
  };
  title: string;
  description?: string;
  status: 'open' | 'in_progress' | 'completed';
  priority: 'low' | 'medium' | 'high';
  dueDate?: Date;
  relatedCustomerId?: {
    _id: string;
    firstName: string;
    lastName: string;
    customerNumber: string;
  };
  relatedContractId?: {
    _id: string;
    contractNumber: string;
    startDate: Date;
    endDate: Date;
  };
  relatedMeterId?: {
    _id: string;
    meterNumber: string;
    type: string;
  };
  isAutoGenerated: boolean;
  autoGenerationType?: 'contract_expiring' | 'contract_expired' | 'reminder_due' | null;
  completedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
  // Support Ticket Fields
  isSupportTicket?: boolean;
  ticketImages?: Array<{
    filename: string;
    originalName: string;
    path: string;
    mimeType: string;
    size: number;
    uploadedAt: Date;
  }>;
  adminResponse?: string;
  adminResponseAt?: Date;
  respondedBy?: {
    _id: string;
    firstName: string;
    lastName: string;
  };
}

export interface CreateTodoDto {
  title: string;
  description?: string;
  status?: 'open' | 'in_progress' | 'completed';
  priority?: 'low' | 'medium' | 'high';
  dueDate?: string;
  relatedCustomerId?: string;
  relatedContractId?: string;
  relatedMeterId?: string;
}

@Injectable({
  providedIn: 'root'
})
export class TodoService {
  private apiUrl = `${environment.apiUrl}/todos`;

  constructor(private http: HttpClient) {}

  getTodos(params?: any): Observable<any> {
    return this.http.get(this.apiUrl, { params });
  }

  getTodo(id: string): Observable<any> {
    return this.http.get(`${this.apiUrl}/${id}`);
  }

  createTodo(data: CreateTodoDto): Observable<any> {
    return this.http.post(this.apiUrl, data);
  }

  updateTodo(id: string, data: Partial<CreateTodoDto>): Observable<any> {
    return this.http.put(`${this.apiUrl}/${id}`, data);
  }

  deleteTodo(id: string): Observable<any> {
    return this.http.delete(`${this.apiUrl}/${id}`);
  }

  completeTodo(id: string): Observable<any> {
    return this.http.put(`${this.apiUrl}/${id}/complete`, {});
  }

  generateExpiringContractTodos(): Observable<any> {
    return this.http.post(`${this.apiUrl}/generate-expiring`, {});
  }

  // Support Ticket Methods
  createSupportTicket(formData: FormData): Observable<any> {
    return this.http.post(`${this.apiUrl}/support-ticket`, formData);
  }

  getSupportTickets(params?: any): Observable<any> {
    return this.http.get(`${this.apiUrl}/support-tickets`, { params });
  }

  respondToSupportTicket(id: string, response: string, status?: string): Observable<any> {
    return this.http.put(`${this.apiUrl}/support-ticket/${id}/respond`, { response, status });
  }

  getSupportTicketImageUrl(ticketId: string, filename: string): string {
    const token = localStorage.getItem('token');
    return `${this.apiUrl}/support-ticket/image/${ticketId}/${filename}?token=${token}`;
  }
}
