const mongoose = require('mongoose');

const todoSchema = new mongoose.Schema({
  beraterId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  title: {
    type: String,
    required: [true, 'Titel ist erforderlich'],
    trim: true
  },
  description: {
    type: String,
    trim: true
  },
  status: {
    type: String,
    enum: ['open', 'in_progress', 'completed'],
    default: 'open'
  },
  priority: {
    type: String,
    enum: ['low', 'medium', 'high'],
    default: 'medium'
  },
  dueDate: {
    type: Date
  },
  // Verknüpfungen zu anderen Entitäten
  relatedCustomerId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Customer',
    default: null
  },
  relatedContractId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Contract',
    default: null
  },
  relatedMeterId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Meter',
    default: null
  },
  // Automatisch generiert oder manuell
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  autoGenerationType: {
    type: String,
    enum: ['contract_expiring', 'contract_expired', 'reminder_due', null],
    default: null
  },
  completedAt: {
    type: Date,
    default: null
  },
  // Support Ticket Felder
  isSupportTicket: {
    type: Boolean,
    default: false
  },
  ticketImages: [{
    filename: String,
    originalName: String,
    path: String,
    mimeType: String,
    size: Number,
    uploadedAt: {
      type: Date,
      default: Date.now
    }
  }],
  // Für Berater: Zusätzliche Informationen/Antwort
  beraterResponse: {
    type: String,
    default: null
  },
  beraterResponseAt: {
    type: Date,
    default: null
  },
  // Für Superadmin: Antwort auf Support-Ticket
  adminResponse: {
    type: String,
    default: null
  },
  adminResponseAt: {
    type: Date,
    default: null
  },
  respondedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  }
}, {
  timestamps: true
});

// Indizes
todoSchema.index({ beraterId: 1, status: 1 });
todoSchema.index({ beraterId: 1, dueDate: 1 });
todoSchema.index({ relatedCustomerId: 1 });
todoSchema.index({ relatedContractId: 1 });

// Setze completedAt wenn Status auf completed gesetzt wird
todoSchema.pre('save', function(next) {
  if (this.isModified('status')) {
    if (this.status === 'completed' && !this.completedAt) {
      this.completedAt = new Date();
    } else if (this.status !== 'completed') {
      this.completedAt = null;
    }
  }
  next();
});

module.exports = mongoose.model('Todo', todoSchema);
