const cron = require('node-cron');
const Todo = require('../models/Todo');
const Contract = require('../models/Contract');

/**
 * Generiert automatisch TODOs für ablaufende Verträge
 * Läuft täglich um 2:00 Uhr morgens
 */
const generateExpiringContractTodos = async () => {
  try {
    console.log('Starte automatische TODO-Generierung für ablaufende Verträge...');

    const today = new Date();
    const daysAhead = 90; // 90 Tage im Voraus
    const futureDate = new Date(today);
    futureDate.setDate(futureDate.getDate() + daysAhead);

    // Finde alle Verträge die in den nächsten 90 Tagen ablaufen
    const expiringContracts = await Contract.find({
      endDate: {
        $gte: today,
        $lte: futureDate
      },
      status: 'active'
    }).populate('customerId', 'firstName lastName');

    let createdCount = 0;

    for (const contract of expiringContracts) {
      // Prüfe ob bereits ein TODO für diesen Vertrag existiert
      const existingTodo = await Todo.findOne({
        beraterId: contract.beraterId,
        relatedContractId: contract._id,
        autoGenerationType: 'contract_expiring',
        status: { $ne: 'completed' }
      });

      if (!existingTodo && contract.customerId) {
        const daysUntilExpiry = Math.ceil((contract.endDate - today) / (1000 * 60 * 60 * 24));

        await Todo.create({
          beraterId: contract.beraterId,
          title: `Vertrag ${contract.contractNumber} läuft ab`,
          description: `Der Vertrag von ${contract.customerId.firstName} ${contract.customerId.lastName} läuft in ${daysUntilExpiry} Tagen ab. Bitte Verlängerung oder Kündigung vorbereiten.`,
          status: 'open',
          priority: daysUntilExpiry <= 30 ? 'high' : daysUntilExpiry <= 60 ? 'medium' : 'low',
          dueDate: contract.endDate,
          relatedCustomerId: contract.customerId,
          relatedContractId: contract._id,
          isAutoGenerated: true,
          autoGenerationType: 'contract_expiring'
        });

        createdCount++;
      }
    }

    console.log(`${createdCount} TODO(s) für ablaufende Verträge erstellt`);
  } catch (error) {
    console.error('Fehler bei automatischer TODO-Generierung:', error);
  }
};

/**
 * Initialisiert alle Cron-Jobs
 */
const initializeJobs = () => {
  // Täglich um 2:00 Uhr morgens
  cron.schedule('0 2 * * *', generateExpiringContractTodos);

  console.log('Cron-Jobs für TODO-Generierung initialisiert');
  console.log('- Ablaufende Verträge: Täglich um 2:00 Uhr');
};

module.exports = {
  initializeJobs,
  generateExpiringContractTodos
};
