const cron = require('node-cron');
const Todo = require('../models/Todo');
const Contract = require('../models/Contract');
const User = require('../models/User');
const { cleanupOldAttachments } = require('./attachmentCleanup');
const { sendContractExpirationReminder, sendPackageExpirationReminder } = require('../services/emailService');

/**
 * Generiert automatisch TODOs für ablaufende Verträge
 * Läuft täglich um 2:00 Uhr morgens
 */
const generateExpiringContractTodos = async () => {
  try {
    console.log('Starte automatische TODO-Generierung für ablaufende Verträge...');

    const today = new Date();
    const daysAhead = 90; // 90 Tage im Voraus
    const futureDate = new Date(today);
    futureDate.setDate(futureDate.getDate() + daysAhead);

    // Finde alle Verträge die in den nächsten 90 Tagen ablaufen
    const expiringContracts = await Contract.find({
      endDate: {
        $gte: today,
        $lte: futureDate
      },
      status: 'active'
    }).populate('customerId', 'firstName lastName');

    let createdCount = 0;
    let emailsSent = 0;

    for (const contract of expiringContracts) {
      // Hole Berater-Daten mit Einstellungen
      const berater = await User.findById(contract.beraterId);
      if (!berater) continue;

      const daysUntilExpiry = Math.ceil((contract.endDate - today) / (1000 * 60 * 60 * 24));

      // Prüfe ob der Berater für diesen Tag eine Erinnerung wünscht
      const reminderDays = berater.settings?.reminderDays?.custom || 30;
      const shouldRemind = daysUntilExpiry === reminderDays;

      if (!shouldRemind) continue;

      // Prüfe ob bereits ein TODO für diesen Vertrag existiert
      const existingTodo = await Todo.findOne({
        beraterId: contract.beraterId,
        relatedContractId: contract._id,
        autoGenerationType: 'contract_expiring',
        status: { $ne: 'completed' }
      });

      if (!existingTodo && contract.customerId) {
        // TODO erstellen
        await Todo.create({
          beraterId: contract.beraterId,
          title: `Vertrag ${contract.contractNumber} läuft ab`,
          description: `Der Vertrag von ${contract.customerId.firstName} ${contract.customerId.lastName} läuft in ${daysUntilExpiry} Tagen ab. Bitte Verlängerung oder Kündigung vorbereiten.`,
          status: 'open',
          priority: daysUntilExpiry <= 30 ? 'high' : daysUntilExpiry <= 60 ? 'medium' : 'low',
          dueDate: contract.endDate,
          relatedCustomerId: contract.customerId,
          relatedContractId: contract._id,
          isAutoGenerated: true,
          autoGenerationType: 'contract_expiring'
        });

        createdCount++;

        // E-Mail senden wenn aktiviert
        if (berater.settings?.reminderDays?.sendEmail) {
          try {
            await sendContractExpirationReminder(berater, contract, daysUntilExpiry);
            emailsSent++;
          } catch (emailError) {
            console.error(`Fehler beim Senden der E-Mail für Vertrag ${contract.contractNumber}:`, emailError.message);
          }
        }
      }
    }

    console.log(`${createdCount} TODO(s) für ablaufende Verträge erstellt`);
    console.log(`${emailsSent} Erinnerungs-E-Mail(s) versendet`);
  } catch (error) {
    console.error('Fehler bei automatischer TODO-Generierung:', error);
  }
};

/**
 * Sendet Erinnerungs-E-Mails für ablaufende Pakete
 * Läuft täglich um 3:00 Uhr morgens
 * Sendet Erinnerungen bei 30, 14, 7, 3 und 1 Tag vor Ablauf
 */
const checkExpiringPackages = async () => {
  try {
    console.log('Prüfe ablaufende Pakete...');

    const today = new Date();
    today.setHours(0, 0, 0, 0);

    // Erinnerungstage vor Ablauf
    const reminderDays = [30, 14, 7, 3, 1];
    let emailsSent = 0;

    // Finde alle Benutzer mit aktivem Paket und Ablaufdatum
    const usersWithSubscription = await User.find({
      'subscription.endDate': { $exists: true, $ne: null },
      'subscription.status': 'active',
      isActive: true,
      isBlocked: false
    });

    for (const user of usersWithSubscription) {
      if (!user.subscription?.endDate) continue;

      const endDate = new Date(user.subscription.endDate);
      endDate.setHours(0, 0, 0, 0);

      const diffTime = endDate.getTime() - today.getTime();
      const daysUntilExpiry = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

      // Prüfe ob heute ein Erinnerungstag ist
      if (reminderDays.includes(daysUntilExpiry)) {
        try {
          await sendPackageExpirationReminder(user, daysUntilExpiry);
          emailsSent++;
          console.log(`Paket-Ablauf-Erinnerung gesendet an ${user.email} (${daysUntilExpiry} Tage verbleibend)`);
        } catch (emailError) {
          console.error(`Fehler beim Senden der Paket-Ablauf-E-Mail an ${user.email}:`, emailError.message);
        }
      }
    }

    console.log(`${emailsSent} Paket-Ablauf-Erinnerung(en) versendet`);
  } catch (error) {
    console.error('Fehler bei Paket-Ablauf-Prüfung:', error);
  }
};

/**
 * Initialisiert alle Cron-Jobs
 */
const initializeJobs = () => {
  // Täglich um 2:00 Uhr morgens - TODO-Generierung
  cron.schedule('0 2 * * *', generateExpiringContractTodos);

  // Täglich um 2:00 Uhr morgens - Anhänge-Cleanup
  cron.schedule('0 2 * * *', cleanupOldAttachments);

  // Täglich um 3:00 Uhr morgens - Paket-Ablauf-Prüfung
  cron.schedule('0 3 * * *', checkExpiringPackages);

  console.log('Cron-Jobs initialisiert:');
  console.log('- Ablaufende Verträge: Täglich um 2:00 Uhr');
  console.log('- Anhänge-Cleanup (>3 Jahre): Täglich um 2:00 Uhr');
  console.log('- Paket-Ablauf-Erinnerungen: Täglich um 3:00 Uhr');
};

module.exports = {
  initializeJobs,
  generateExpiringContractTodos,
  checkExpiringPackages
};
