import { CommonModule } from "@angular/common";
import { Component, EventEmitter, Input, Output } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { Data } from "@angular/router";
import { Todo } from "src/app/services/todo.service";

@Component({
    selector: 'app-todo',
    imports: [CommonModule, FormsModule],
    template: `
  @if(todo) {
    <div class="todo-card" [class.priority-high]="todo.priority === 'high'"
        [class.priority-medium]="todo.priority === 'medium'" [class.priority-low]="todo.priority === 'low'"
        [class.completed]="todo.status === 'completed'">

        <div class="todo-header">
            <div class="todo-badges">
                <span class="badge badge-priority" [class]="'priority-' + todo.priority">
                    {{ getPriorityLabel(todo.priority) }}
                </span>
                <span class="badge badge-status" [class]="'status-' + todo.status">
                    {{ getStatusLabel(todo.status) }}
                </span>
                <span *ngIf="todo.isAutoGenerated" class="badge badge-auto">Automatisch</span>
            </div>
            <button class="btn-icon" (click)="deleteTodo(todo._id)">&times;</button>
        </div>

        <h3 class="todo-title">{{ todo.title }}</h3>
        <p *ngIf="todo.description" class="todo-description">{{ todo.description }}</p>

        <div class="todo-meta">
            <div *ngIf="todo.dueDate" class="due-date" [class.overdue]="isOverdue(todo.dueDate)">
                <span class="icon">📅</span>
                <span>{{ todo.dueDate | date:'dd.MM.yyyy' }}</span>
                <span *ngIf="isOverdue(todo.dueDate)" class="overdue-label">Überfällig</span>
            </div>
        </div>

        <div class="todo-relations" *ngIf="hasRelations(todo)">
            <div *ngIf="todo.relatedCustomerId && todo.relatedCustomerId.firstName" class="relation-item">
                <span class="relation-icon">👤</span>
                <a (click)="navigateToCustomer(todo.relatedCustomerId._id)" class="relation-link">
                    {{ todo.relatedCustomerId.firstName }} {{ todo.relatedCustomerId.lastName }}
                </a>
            </div>
            <div *ngIf="todo.relatedContractId && todo.relatedContractId.contractNumber" class="relation-item">
                <span class="relation-icon">📄</span>
                <a (click)="navigateToContract(todo.relatedContractId._id)" class="relation-link">
                    Vertrag {{ todo.relatedContractId.contractNumber }}
                </a>
            </div>
            <div *ngIf="todo.relatedMeterId && todo.relatedMeterId.meterNumber" class="relation-item">
                <span class="relation-icon">⚡</span>
                <a (click)="navigateToMeter(todo.relatedMeterId._id)" class="relation-link">
                    Zähler {{ todo.relatedMeterId.meterNumber }}
                </a>
            </div>
        </div>

        <div class="todo-actions">
            <button *ngIf="todo.status !== 'completed'" class="btn-small btn-success"
                (click)="completeTodo(todo._id)">
                ✓ Erledigen
            </button>
            <button class="btn-small" (click)="editTodo(todo)">Bearbeiten</button>
        </div>
    </div>
  }
`,
    styles: [
        `
        .todo-card {
            background: white;
            border-radius: 12px;
            padding: 1.5rem;
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
            border-left: 4px solid #667eea;
            transition: all 0.3s;
        }
        .todo-card:hover {
            box-shadow: 0 4px 16px rgba(0, 0, 0, 0.15);
            transform: translateY(-2px);
        }
        .todo-card.priority-high { border-left-color: #e74c3c; }
        .todo-card.priority-medium { border-left-color: #f39c12; }
        .todo-card.priority-low { border-left-color: #3498db; }
        .todo-card.completed { opacity: 0.6; }
        .todo-header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            margin-bottom: 1rem;
        }
        .todo-badges {
            display: flex;
            gap: 0.5rem;
            flex-wrap: wrap;
        }
        .todo-actions {
            display: flex;
            gap: 0.5rem;
            margin-top: 1rem;
        }
        .btn-icon {
            background: none;
            border: none;
            font-size: 1.5rem;
            cursor: pointer;
            color: #999;
            line-height: 1;
            padding: 0;
        }
    .btn-icon:hover { color: #c62828; }
        .btn-primary, .btn-secondary, .btn-small, .btn-success {
            padding: 0.625rem 1.25rem;
            border: none;
            border-radius: 8px;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.3s;
        }
    `
    ]
})
export class TodoComponent {

    @Input() todo: any;
    @Output() deleteTodoEmiter = new EventEmitter<string>();
    @Output() completeTodoEmiter = new EventEmitter<string>();
    @Output() editTodoEmiter = new EventEmitter<Todo>();
    @Output() overdueEmiter = new EventEmitter<Data>();
    @Output() navigateToCustomerEmiter = new EventEmitter<string>();
    @Output() navigateToContractEmiter = new EventEmitter<string>();
    @Output() navigateToMeterEmiter = new EventEmitter<string>();

    getPriorityLabel(priority: string): string {
        const labels: any = {
            high: 'Hoch',
            medium: 'Mittel',
            low: 'Niedrig'
        };
        return labels[priority] || priority;
    }
    getStatusLabel(status: string): string {
        const labels: any = {
            open: 'Offen',
            in_progress: 'In Bearbeitung',
            completed: 'Erledigt'
        };
        return labels[status] || status;
    }
    hasRelations(todo: Todo): boolean {
        return !!(
            (todo.relatedCustomerId && typeof todo.relatedCustomerId === 'object' && todo.relatedCustomerId.firstName) ||
            (todo.relatedContractId && typeof todo.relatedContractId === 'object' && todo.relatedContractId.contractNumber) ||
            (todo.relatedMeterId && typeof todo.relatedMeterId === 'object' && todo.relatedMeterId.meterNumber)
        );
    }
    deleteTodo(id: string) {
        this.deleteTodoEmiter.emit(id);
    }
    completeTodo(id: string) {
        this.completeTodoEmiter.emit(id);
    }
    editTodo(todo: Todo) {
        this.editTodoEmiter.emit(todo);
    }
      isOverdue(dueDate: Date): boolean {
    if (!dueDate) return false;
    return new Date(dueDate) < new Date();
  }
    navigateToCustomer(id: string) {
        this.navigateToCustomerEmiter.emit(id);
    }
    navigateToContract(id: string) {
        this.navigateToContractEmiter.emit(id);
    }
    navigateToMeter(id: string) {
        this.navigateToMeterEmiter.emit(id);
    }
} 