import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { TodoService, Todo, CreateTodoDto } from '../../services/todo.service';
import { CustomerService } from '../../services/customer.service';
import { ContractService } from '../../services/contract.service';
import { MeterService } from '../../services/meter.service';

@Component({
  selector: 'app-todos',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="page-container">
      <div class="page-header">
        <h1>TODOs</h1>
        <div class="header-actions">
          <button class="btn-secondary" (click)="generateAutoTodos()">Automatische TODOs generieren</button>
          <button class="btn-primary" (click)="showCreateModal()">+ Neues TODO</button>
        </div>
      </div>

      <div class="filters">
        <input
          type="text"
          [(ngModel)]="searchTerm"
          (ngModelChange)="filterTodos()"
          placeholder="Suchen..."
          class="search-input"
        />
        <select [(ngModel)]="statusFilter" (ngModelChange)="filterTodos()" class="filter-select">
          <option value="">Alle Status</option>
          <option value="open">Offen</option>
          <option value="in_progress">In Bearbeitung</option>
          <option value="completed">Erledigt</option>
        </select>
        <select [(ngModel)]="priorityFilter" (ngModelChange)="filterTodos()" class="filter-select">
          <option value="">Alle Prioritäten</option>
          <option value="high">Hoch</option>
          <option value="medium">Mittel</option>
          <option value="low">Niedrig</option>
        </select>
      </div>

      <div class="todos-grid">
        <div *ngFor="let todo of filteredTodos"
             class="todo-card"
             [class.priority-high]="todo.priority === 'high'"
             [class.priority-medium]="todo.priority === 'medium'"
             [class.priority-low]="todo.priority === 'low'"
             [class.completed]="todo.status === 'completed'">

          <div class="todo-header">
            <div class="todo-badges">
              <span class="badge badge-priority" [class]="'priority-' + todo.priority">
                {{ getPriorityLabel(todo.priority) }}
              </span>
              <span class="badge badge-status" [class]="'status-' + todo.status">
                {{ getStatusLabel(todo.status) }}
              </span>
              <span *ngIf="todo.isAutoGenerated" class="badge badge-auto">Automatisch</span>
            </div>
            <button class="btn-icon" (click)="deleteTodo(todo._id)">&times;</button>
          </div>

          <h3 class="todo-title">{{ todo.title }}</h3>
          <p *ngIf="todo.description" class="todo-description">{{ todo.description }}</p>

          <div class="todo-meta">
            <div *ngIf="todo.dueDate" class="due-date" [class.overdue]="isOverdue(todo.dueDate)">
              <span class="icon">📅</span>
              <span>{{ todo.dueDate | date:'dd.MM.yyyy' }}</span>
              <span *ngIf="isOverdue(todo.dueDate)" class="overdue-label">Überfällig</span>
            </div>
          </div>

          <div class="todo-relations" *ngIf="hasRelations(todo)">
            <div *ngIf="todo.relatedCustomerId && todo.relatedCustomerId.firstName" class="relation-item">
              <span class="relation-icon">👤</span>
              <a (click)="navigateToCustomer(todo.relatedCustomerId._id)" class="relation-link">
                {{ todo.relatedCustomerId.firstName }} {{ todo.relatedCustomerId.lastName }}
              </a>
            </div>
            <div *ngIf="todo.relatedContractId && todo.relatedContractId.contractNumber" class="relation-item">
              <span class="relation-icon">📄</span>
              <a (click)="navigateToContract(todo.relatedContractId._id)" class="relation-link">
                Vertrag {{ todo.relatedContractId.contractNumber }}
              </a>
            </div>
            <div *ngIf="todo.relatedMeterId && todo.relatedMeterId.meterNumber" class="relation-item">
              <span class="relation-icon">⚡</span>
              <a (click)="navigateToMeter(todo.relatedMeterId._id)" class="relation-link">
                Zähler {{ todo.relatedMeterId.meterNumber }}
              </a>
            </div>
          </div>

          <div class="todo-actions">
            <button *ngIf="todo.status !== 'completed'"
                    class="btn-small btn-success"
                    (click)="completeTodo(todo._id)">
              ✓ Erledigen
            </button>
            <button class="btn-small" (click)="editTodo(todo)">Bearbeiten</button>
          </div>
        </div>

        <div *ngIf="filteredTodos.length === 0" class="no-data">
          <p>Keine TODOs gefunden</p>
        </div>
      </div>

      <!-- Modal for Create/Edit TODO -->
      <div class="modal-overlay" *ngIf="showModal" (click)="closeModal()">
        <div class="modal-content" (click)="$event.stopPropagation()">
          <div class="modal-header">
            <h2>{{ isEditMode ? 'TODO bearbeiten' : 'Neues TODO' }}</h2>
            <button class="btn-close" (click)="closeModal()">&times;</button>
          </div>

          <form (ngSubmit)="saveTodo()" #todoForm="ngForm">
            <div class="form-group">
              <label for="title">Titel *</label>
              <input
                type="text"
                id="title"
                name="title"
                [(ngModel)]="currentTodo.title"
                required
                class="form-control"
                placeholder="z.B. Adresse von Kunde ändern"
              />
            </div>

            <div class="form-group">
              <label for="description">Beschreibung</label>
              <textarea
                id="description"
                name="description"
                [(ngModel)]="currentTodo.description"
                rows="4"
                class="form-control"
                placeholder="Zusätzliche Details..."
              ></textarea>
            </div>

            <div class="form-row">
              <div class="form-group">
                <label for="priority">Priorität</label>
                <select id="priority" name="priority" [(ngModel)]="currentTodo.priority" class="form-control">
                  <option value="low">Niedrig</option>
                  <option value="medium">Mittel</option>
                  <option value="high">Hoch</option>
                </select>
              </div>

              <div class="form-group">
                <label for="status">Status</label>
                <select id="status" name="status" [(ngModel)]="currentTodo.status" class="form-control">
                  <option value="open">Offen</option>
                  <option value="in_progress">In Bearbeitung</option>
                  <option value="completed">Erledigt</option>
                </select>
              </div>
            </div>

            <div class="form-group">
              <label for="dueDate">Fälligkeitsdatum</label>
              <input
                type="date"
                id="dueDate"
                name="dueDate"
                [(ngModel)]="currentTodo.dueDate"
                class="form-control"
              />
            </div>

            <div class="form-section">
              <h3>Verknüpfungen (optional)</h3>

              <div class="form-group">
                <label for="relatedCustomerId">Kunde</label>
                <select id="relatedCustomerId" name="relatedCustomerId"
                        [(ngModel)]="currentTodo.relatedCustomerId"
                        class="form-control">
                  <option [ngValue]="null">Kein Kunde</option>
                  <option *ngFor="let customer of customers" [value]="customer._id">
                    {{ customer.firstName }} {{ customer.lastName }} ({{ customer.customerNumber }})
                  </option>
                </select>
              </div>

              <div class="form-group">
                <label for="relatedContractId">Vertrag</label>
                <select id="relatedContractId" name="relatedContractId"
                        [(ngModel)]="currentTodo.relatedContractId"
                        class="form-control">
                  <option [ngValue]="null">Kein Vertrag</option>
                  <option *ngFor="let contract of contracts" [value]="contract._id">
                    {{ contract.contractNumber }} - {{ contract.customerId?.firstName }} {{ contract.customerId?.lastName }}
                  </option>
                </select>
              </div>

              <div class="form-group">
                <label for="relatedMeterId">Zähler</label>
                <select id="relatedMeterId" name="relatedMeterId"
                        [(ngModel)]="currentTodo.relatedMeterId"
                        class="form-control">
                  <option [ngValue]="null">Kein Zähler</option>
                  <option *ngFor="let meter of meters" [value]="meter._id">
                    {{ meter.meterNumber }} ({{ getTypeLabel(meter.type) }})
                  </option>
                </select>
              </div>
            </div>

            <div class="modal-footer">
              <button type="button" class="btn-secondary" (click)="closeModal()">Abbrechen</button>
              <button type="submit" class="btn-primary" [disabled]="!todoForm.form.valid">
                {{ isEditMode ? 'Speichern' : 'Erstellen' }}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .page-container { padding: 2rem; }
    .page-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 2rem;
    }
    .header-actions {
      display: flex;
      gap: 1rem;
    }
    h1 { font-size: 2rem; color: #333; margin: 0; }
    .filters {
      display: flex;
      gap: 1rem;
      margin-bottom: 2rem;
    }
    .search-input, .filter-select {
      padding: 0.75rem;
      border: 2px solid #e0e0e0;
      border-radius: 8px;
      font-size: 1rem;
    }
    .search-input {
      flex: 1;
      max-width: 400px;
    }
    .todos-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
      gap: 1.5rem;
    }
    .todo-card {
      background: white;
      border-radius: 12px;
      padding: 1.5rem;
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
      border-left: 4px solid #667eea;
      transition: all 0.3s;
    }
    .todo-card:hover {
      box-shadow: 0 4px 16px rgba(0, 0, 0, 0.15);
      transform: translateY(-2px);
    }
    .todo-card.priority-high { border-left-color: #e74c3c; }
    .todo-card.priority-medium { border-left-color: #f39c12; }
    .todo-card.priority-low { border-left-color: #3498db; }
    .todo-card.completed { opacity: 0.6; }
    .todo-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 1rem;
    }
    .todo-badges {
      display: flex;
      gap: 0.5rem;
      flex-wrap: wrap;
    }
    .badge {
      display: inline-block;
      padding: 0.25rem 0.75rem;
      border-radius: 12px;
      font-size: 0.75rem;
      font-weight: 600;
    }
    .badge-priority.priority-high { background: #ffebee; color: #c62828; }
    .badge-priority.priority-medium { background: #fff3e0; color: #e65100; }
    .badge-priority.priority-low { background: #e3f2fd; color: #1565c0; }
    .badge-status.status-open { background: #f5f5f5; color: #666; }
    .badge-status.status-in_progress { background: #e8f5e9; color: #2e7d32; }
    .badge-status.status-completed { background: #e0e0e0; color: #424242; }
    .badge-auto { background: #ede7f6; color: #5e35b1; }
    .btn-icon {
      background: none;
      border: none;
      font-size: 1.5rem;
      cursor: pointer;
      color: #999;
      line-height: 1;
      padding: 0;
    }
    .btn-icon:hover { color: #c62828; }
    .todo-title {
      margin: 0 0 0.5rem 0;
      font-size: 1.25rem;
      color: #333;
    }
    .todo-description {
      color: #666;
      font-size: 0.95rem;
      margin: 0 0 1rem 0;
      line-height: 1.5;
    }
    .todo-meta {
      margin-bottom: 1rem;
    }
    .due-date {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      color: #666;
      font-size: 0.9rem;
    }
    .due-date.overdue {
      color: #c62828;
      font-weight: 600;
    }
    .overdue-label {
      background: #ffebee;
      color: #c62828;
      padding: 0.125rem 0.5rem;
      border-radius: 8px;
      font-size: 0.75rem;
    }
    .todo-relations {
      background: #f8f9fa;
      border-radius: 8px;
      padding: 0.75rem;
      margin-bottom: 1rem;
    }
    .relation-item {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      margin-bottom: 0.5rem;
    }
    .relation-item:last-child {
      margin-bottom: 0;
    }
    .relation-icon {
      font-size: 1rem;
    }
    .relation-link {
      color: #667eea;
      cursor: pointer;
      text-decoration: underline;
      font-size: 0.9rem;
    }
    .relation-link:hover {
      color: #5568d3;
    }
    .todo-actions {
      display: flex;
      gap: 0.5rem;
      margin-top: 1rem;
    }
    .btn-primary, .btn-secondary, .btn-small, .btn-success {
      padding: 0.625rem 1.25rem;
      border: none;
      border-radius: 8px;
      font-weight: 600;
      cursor: pointer;
      transition: all 0.3s;
    }
    .btn-primary {
      background: #667eea;
      color: white;
    }
    .btn-primary:hover { background: #5568d3; }
    .btn-secondary {
      background: #e0e0e0;
      color: #555;
    }
    .btn-secondary:hover { background: #d0d0d0; }
    .btn-small {
      padding: 0.4rem 0.8rem;
      font-size: 0.875rem;
      background: #f0f0f0;
      color: #555;
    }
    .btn-small:hover { background: #e0e0e0; }
    .btn-success {
      background: #4caf50;
      color: white;
      font-size: 0.875rem;
      padding: 0.4rem 0.8rem;
    }
    .btn-success:hover { background: #45a049; }
    .modal-overlay {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background: rgba(0, 0, 0, 0.5);
      display: flex;
      align-items: center;
      justify-content: center;
      z-index: 1000;
    }
    .modal-content {
      background: white;
      border-radius: 12px;
      padding: 2rem;
      width: 90%;
      max-width: 600px;
      max-height: 90vh;
      overflow-y: auto;
      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);
    }
    .modal-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 1.5rem;
      padding-bottom: 1rem;
      border-bottom: 2px solid #e0e0e0;
    }
    .modal-header h2 {
      margin: 0;
      font-size: 1.5rem;
      color: #333;
    }
    .btn-close {
      background: none;
      border: none;
      font-size: 2rem;
      cursor: pointer;
      color: #888;
      line-height: 1;
      padding: 0;
      width: 30px;
      height: 30px;
    }
    .btn-close:hover { color: #333; }
    .form-group {
      margin-bottom: 1.5rem;
    }
    .form-group label {
      display: block;
      margin-bottom: 0.5rem;
      font-weight: 600;
      color: #555;
    }
    .form-control {
      width: 100%;
      padding: 0.75rem;
      border: 2px solid #e0e0e0;
      border-radius: 8px;
      font-size: 1rem;
      transition: border-color 0.3s;
      box-sizing: border-box;
    }
    .form-control:focus {
      outline: none;
      border-color: #667eea;
    }
    .form-row {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 1rem;
    }
    .form-section {
      margin-top: 2rem;
      padding-top: 1.5rem;
      border-top: 2px solid #e0e0e0;
    }
    .form-section h3 {
      margin: 0 0 1rem 0;
      font-size: 1.1rem;
      color: #555;
    }
    .modal-footer {
      display: flex;
      justify-content: flex-end;
      gap: 1rem;
      margin-top: 2rem;
      padding-top: 1.5rem;
      border-top: 2px solid #e0e0e0;
    }
    button:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }
    .no-data {
      text-align: center;
      padding: 4rem 2rem;
      color: #888;
      font-size: 1.1rem;
      grid-column: 1 / -1;
    }
  `]
})
export class TodosComponent implements OnInit {
  todos: Todo[] = [];
  filteredTodos: Todo[] = [];
  searchTerm = '';
  statusFilter = '';
  priorityFilter = '';
  showModal = false;
  isEditMode = false;
  currentTodo: any = this.getEmptyTodo();

  // Daten für Verknüpfungen
  customers: any[] = [];
  contracts: any[] = [];
  meters: any[] = [];

  constructor(
    private todoService: TodoService,
    private customerService: CustomerService,
    private contractService: ContractService,
    private meterService: MeterService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.loadTodos();
    this.loadRelatedData();
  }

  loadTodos(): void {
    this.todoService.getTodos().subscribe({
      next: (response) => {
        if (response.success) {
          this.todos = response.data;
          this.filterTodos();
        }
      },
      error: (error) => {
        console.error('Fehler beim Laden der TODOs:', error);
      }
    });
  }

  loadRelatedData(): void {
    // Lade Kunden für Dropdown
    this.customerService.getCustomers().subscribe({
      next: (response) => {
        if (response.success) {
          this.customers = response.data;
        }
      }
    });

    // Lade Verträge für Dropdown
    this.contractService.getContracts().subscribe({
      next: (response) => {
        if (response.success) {
          this.contracts = response.data;
        }
      }
    });

    // Lade Zähler für Dropdown
    this.meterService.getMeters().subscribe({
      next: (response) => {
        if (response.success) {
          this.meters = response.data;
        }
      }
    });
  }

  filterTodos(): void {
    this.filteredTodos = this.todos.filter(todo => {
      const matchesSearch = !this.searchTerm ||
        todo.title.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
        (todo.description && todo.description.toLowerCase().includes(this.searchTerm.toLowerCase()));

      const matchesStatus = !this.statusFilter || todo.status === this.statusFilter;
      const matchesPriority = !this.priorityFilter || todo.priority === this.priorityFilter;

      return matchesSearch && matchesStatus && matchesPriority;
    });
  }

  getEmptyTodo(): CreateTodoDto {
    return {
      title: '',
      description: '',
      status: 'open',
      priority: 'medium',
      dueDate: '',
      relatedCustomerId: undefined,
      relatedContractId: undefined,
      relatedMeterId: undefined
    };
  }

  showCreateModal(): void {
    this.currentTodo = this.getEmptyTodo();
    this.isEditMode = false;
    this.showModal = true;
  }

  editTodo(todo: Todo): void {
    this.currentTodo = {
      _id: todo._id,
      title: todo.title,
      description: todo.description || '',
      status: todo.status,
      priority: todo.priority,
      dueDate: todo.dueDate ? new Date(todo.dueDate).toISOString().split('T')[0] : '',
      relatedCustomerId: todo.relatedCustomerId?._id || null,
      relatedContractId: todo.relatedContractId?._id || null,
      relatedMeterId: todo.relatedMeterId?._id || null
    };
    this.isEditMode = true;
    this.showModal = true;
  }

  closeModal(): void {
    this.showModal = false;
    this.currentTodo = this.getEmptyTodo();
    this.isEditMode = false;
  }

  saveTodo(): void {
    const todoData = { ...this.currentTodo };

    // Entferne null-Werte für optionale Felder
    if (!todoData.relatedCustomerId) delete todoData.relatedCustomerId;
    if (!todoData.relatedContractId) delete todoData.relatedContractId;
    if (!todoData.relatedMeterId) delete todoData.relatedMeterId;
    if (!todoData.dueDate) delete todoData.dueDate;

    if (this.isEditMode) {
      this.todoService.updateTodo(this.currentTodo._id, todoData).subscribe({
        next: (response) => {
          if (response.success) {
            this.loadTodos();
            this.closeModal();
          }
        },
        error: (error) => {
          alert('Fehler beim Speichern: ' + (error.error?.message || 'Unbekannter Fehler'));
        }
      });
    } else {
      this.todoService.createTodo(todoData).subscribe({
        next: (response) => {
          if (response.success) {
            this.loadTodos();
            this.closeModal();
          }
        },
        error: (error) => {
          alert('Fehler beim Erstellen: ' + (error.error?.message || 'Unbekannter Fehler'));
        }
      });
    }
  }

  deleteTodo(id: string): void {
    if (!confirm('Möchten Sie dieses TODO wirklich löschen?')) {
      return;
    }

    this.todoService.deleteTodo(id).subscribe({
      next: (response) => {
        if (response.success) {
          this.loadTodos();
        }
      },
      error: (error) => {
        alert('Fehler beim Löschen: ' + (error.error?.message || 'Unbekannter Fehler'));
      }
    });
  }

  completeTodo(id: string): void {
    this.todoService.completeTodo(id).subscribe({
      next: (response) => {
        if (response.success) {
          this.loadTodos();
        }
      },
      error: (error) => {
        alert('Fehler beim Abschließen: ' + (error.error?.message || 'Unbekannter Fehler'));
      }
    });
  }

  generateAutoTodos(): void {
    if (!confirm('Möchten Sie automatische TODOs für ablaufende Verträge generieren?')) {
      return;
    }

    this.todoService.generateExpiringContractTodos().subscribe({
      next: (response) => {
        if (response.success) {
          alert(response.message);
          this.loadTodos();
        }
      },
      error: (error) => {
        alert('Fehler beim Generieren: ' + (error.error?.message || 'Unbekannter Fehler'));
      }
    });
  }

  navigateToCustomer(customerId: string): void {
    // Navigation zur Kunden-Detailseite
    this.router.navigate(['/customers', customerId]);
  }

  navigateToContract(contractId: string): void {
    // Navigation zur Vertrags-Detailseite
    this.router.navigate(['/contracts', contractId]);
  }

  navigateToMeter(meterId: string): void {
    // Navigation zur Zähler-Detailseite
    this.router.navigate(['/meters', meterId]);
  }

  getPriorityLabel(priority: string): string {
    const labels: any = {
      high: 'Hoch',
      medium: 'Mittel',
      low: 'Niedrig'
    };
    return labels[priority] || priority;
  }

  getStatusLabel(status: string): string {
    const labels: any = {
      open: 'Offen',
      in_progress: 'In Bearbeitung',
      completed: 'Erledigt'
    };
    return labels[status] || status;
  }

  getTypeLabel(type: string): string {
    const labels: any = {
      electricity: 'Strom',
      gas: 'Gas',
      water: 'Wasser'
    };
    return labels[type] || type;
  }

  isOverdue(dueDate: Date): boolean {
    if (!dueDate) return false;
    return new Date(dueDate) < new Date();
  }

  hasRelations(todo: Todo): boolean {
    return !!(
      (todo.relatedCustomerId && typeof todo.relatedCustomerId === 'object' && todo.relatedCustomerId.firstName) ||
      (todo.relatedContractId && typeof todo.relatedContractId === 'object' && todo.relatedContractId.contractNumber) ||
      (todo.relatedMeterId && typeof todo.relatedMeterId === 'object' && todo.relatedMeterId.meterNumber)
    );
  }
}
