import { CommonModule } from "@angular/common";
import { Component, EventEmitter, Input, Output } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { Data } from "@angular/router";
import { Todo } from "src/app/services/todo.service";

@Component({
    selector: 'app-todo',
    imports: [CommonModule, FormsModule],
    template: `
  @if(todo) {
    <div class="todo-card" [class.completed]="todo.status === 'completed'" (click)="editTodo(todo)">
        <div class="todo-header">
            <div class="todo-title-section">
                <i class="fas fa-check-circle"></i>
                <h3 class="todo-title">{{ todo.title }}</h3>
            </div>
            <span class="badge badge-priority"
                  [class.badge-high]="todo.priority === 'high'"
                  [class.badge-medium]="todo.priority === 'medium'"
                  [class.badge-low]="todo.priority === 'low'">
                {{ getPriorityLabel(todo.priority) }}
            </span>
        </div>

        <p *ngIf="todo.description" class="todo-description">{{ todo.description }}</p>

        <div class="todo-meta" *ngIf="todo.dueDate || todo.isAutoGenerated">
            <div *ngIf="todo.dueDate" class="due-date" [class.overdue]="isOverdue(todo.dueDate)">
                <i class="fas fa-calendar-alt"></i>
                <span>{{ todo.dueDate | date:'dd.MM.yyyy' }}</span>
                <span *ngIf="isOverdue(todo.dueDate)" class="overdue-badge">Überfällig</span>
            </div>
            <span *ngIf="todo.isAutoGenerated" class="auto-badge">
                <i class="fas fa-magic"></i> Automatisch
            </span>
        </div>

        <div class="todo-relations" *ngIf="hasRelations(todo)">
            <div *ngIf="todo.relatedCustomerId && todo.relatedCustomerId.firstName" class="relation-item">
                <i class="fas fa-user"></i>
                <span class="relation-link" (click)="navigateToCustomer(todo.relatedCustomerId._id); $event.stopPropagation()">
                    {{ todo.relatedCustomerId.firstName }} {{ todo.relatedCustomerId.lastName }}
                </span>
            </div>
            <div *ngIf="todo.relatedContractId && todo.relatedContractId.contractNumber" class="relation-item">
                <i class="fas fa-file-contract"></i>
                <span class="relation-link" (click)="navigateToContract(todo.relatedContractId._id); $event.stopPropagation()">
                    Vertrag {{ todo.relatedContractId.contractNumber }}
                </span>
            </div>
            <div *ngIf="todo.relatedMeterId && todo.relatedMeterId.meterNumber" class="relation-item">
                <i class="fas fa-tachometer-alt"></i>
                <span class="relation-link" (click)="navigateToMeter(todo.relatedMeterId._id); $event.stopPropagation()">
                    Zähler {{ todo.relatedMeterId.meterNumber }}
                </span>
            </div>
        </div>

        <div class="todo-footer">
            <span class="todo-status"
                  [class.status-open]="todo.status === 'open'"
                  [class.status-progress]="todo.status === 'in_progress'"
                  [class.status-completed]="todo.status === 'completed'">
                {{ getStatusLabel(todo.status) }}
            </span>

            <div class="todo-actions" (click)="$event.stopPropagation()">
                <button *ngIf="todo.status !== 'completed'" class="action-btn complete-btn"
                        (click)="completeTodo(todo._id)" title="Als erledigt markieren">
                    <i class="fas fa-check"></i>
                </button>
                <button class="action-btn delete-btn" (click)="deleteTodo(todo._id)" title="Löschen">
                    <i class="fas fa-trash"></i>
                </button>
            </div>
        </div>
    </div>
  }
`,
    styles: [
        `
        .todo-card {
            background: white;
            border: 1px solid #e0e0e0;
            border-radius: 12px;
            padding: 1.5rem;
            cursor: pointer;
            transition: all 0.3s;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
        }
        .todo-card:hover {
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.12);
            transform: translateY(-4px);
            border-color: #34d399;
        }
        .todo-card.completed {
            opacity: 0.7;
            background: #f8f9fa;
        }

        .todo-header {
            display: flex;
            justify-content: space-between;
            align-items: start;
            margin-bottom: 1rem;
            gap: 1rem;
        }

        .todo-title-section {
            display: flex;
            align-items: center;
            gap: 0.5rem;
            flex: 1;

            i {
                color: #34d399;
                font-size: 1rem;
            }
        }

        .todo-title {
            margin: 0;
            font-size: 1.1rem;
            font-weight: 600;
            color: #333;
            word-break: break-word;
        }

        .badge-priority {
            padding: 0.35rem 0.85rem;
            border-radius: 16px;
            font-size: 0.75rem;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.3px;
            white-space: nowrap;
        }

        .badge-high {
            background: linear-gradient(135deg, #ff6b6b 0%, #dc3545 100%);
            color: white;
            box-shadow: 0 2px 8px rgba(220, 53, 69, 0.3);
        }

        .badge-medium {
            background: linear-gradient(135deg, #ffd93d 0%, #ffc107 100%);
            color: #664d03;
            box-shadow: 0 2px 8px rgba(255, 193, 7, 0.3);
        }

        .badge-low {
            background: linear-gradient(135deg, #6dd5ed 0%, #34d399 100%);
            color: white;
            box-shadow: 0 2px 8px rgba(52, 211, 153, 0.3);
        }

        .todo-description {
            color: #666;
            margin: 1rem 0;
            display: -webkit-box;
            -webkit-line-clamp: 3;
            -webkit-box-orient: vertical;
            overflow: hidden;
            line-height: 1.5;
        }

        .todo-meta {
            display: flex;
            align-items: center;
            gap: 1rem;
            flex-wrap: wrap;
            margin-bottom: 1rem;
        }

        .due-date {
            display: flex;
            align-items: center;
            gap: 0.5rem;
            color: #666;
            font-size: 0.9rem;

            i {
                color: #999;
            }

            &.overdue {
                color: #dc3545;
                font-weight: 600;

                i {
                    color: #dc3545;
                }
            }
        }

        .overdue-badge {
            background: #ffebee;
            color: #c62828;
            padding: 0.25rem 0.5rem;
            border-radius: 8px;
            font-size: 0.75rem;
            font-weight: 600;
        }

        .auto-badge {
            background: #ede7f6;
            color: #5e35b1;
            padding: 0.35rem 0.75rem;
            border-radius: 12px;
            font-size: 0.75rem;
            font-weight: 600;
            display: flex;
            align-items: center;
            gap: 0.35rem;
        }

        .todo-relations {
            background: #f8f9fa;
            border-radius: 8px;
            padding: 0.75rem;
            margin-bottom: 1rem;
        }

        .relation-item {
            display: flex;
            align-items: center;
            gap: 0.5rem;
            margin-bottom: 0.5rem;
            font-size: 0.9rem;

            &:last-child {
                margin-bottom: 0;
            }

            i {
                color: #34d399;
                font-size: 0.9rem;
            }
        }

        .relation-link {
            color: #34d399;
            cursor: pointer;
            text-decoration: underline;

            &:hover {
                color: #2c9f7f;
            }
        }

        .todo-footer {
            display: flex;
            align-items: center;
            justify-content: space-between;
            margin-top: 1rem;
            padding-top: 1rem;
            border-top: 1px solid #f0f0f0;
        }

        .todo-status {
            padding: 0.35rem 0.85rem;
            border-radius: 16px;
            font-size: 0.85rem;
            font-weight: 600;
        }

        .status-open {
            background: linear-gradient(135deg, #fff3cd 0%, #ffe69c 100%);
            color: #856404;
            border: 1px solid #ffc107;
        }

        .status-progress {
            background: linear-gradient(135deg, #cfe2ff 0%, #9ec5fe 100%);
            color: #084298;
            border: 1px solid #0d6efd;
        }

        .status-completed {
            background: linear-gradient(135deg, #d1e7dd 0%, #a3cfbb 100%);
            color: #0a3622;
            border: 1px solid #198754;
        }

        .todo-actions {
            display: flex;
            gap: 0.5rem;
        }

        .action-btn {
            width: 36px;
            height: 36px;
            border: none;
            border-radius: 8px;
            display: flex;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            transition: all 0.2s;
            font-size: 0.9rem;
        }

        .complete-btn {
            background: #e8f5e9;
            color: #2e7d32;

            &:hover {
                background: #2e7d32;
                color: white;
            }
        }

        .delete-btn {
            background: #ffebee;
            color: #c62828;

            &:hover {
                background: #c62828;
                color: white;
            }
        }
    `
    ]
})
export class TodoComponent {

    @Input() todo: any;
    @Output() deleteTodoEmiter = new EventEmitter<string>();
    @Output() completeTodoEmiter = new EventEmitter<string>();
    @Output() editTodoEmiter = new EventEmitter<Todo>();
    @Output() overdueEmiter = new EventEmitter<Data>();
    @Output() navigateToCustomerEmiter = new EventEmitter<string>();
    @Output() navigateToContractEmiter = new EventEmitter<string>();
    @Output() navigateToMeterEmiter = new EventEmitter<string>();

    getPriorityLabel(priority: string): string {
        const labels: any = {
            high: 'Hoch',
            medium: 'Mittel',
            low: 'Niedrig'
        };
        return labels[priority] || priority;
    }
    getStatusLabel(status: string): string {
        const labels: any = {
            open: 'Offen',
            in_progress: 'In Bearbeitung',
            completed: 'Erledigt'
        };
        return labels[status] || status;
    }
    hasRelations(todo: Todo): boolean {
        return !!(
            (todo.relatedCustomerId && typeof todo.relatedCustomerId === 'object' && todo.relatedCustomerId.firstName) ||
            (todo.relatedContractId && typeof todo.relatedContractId === 'object' && todo.relatedContractId.contractNumber) ||
            (todo.relatedMeterId && typeof todo.relatedMeterId === 'object' && todo.relatedMeterId.meterNumber)
        );
    }
    deleteTodo(id: string) {
        this.deleteTodoEmiter.emit(id);
    }
    completeTodo(id: string) {
        this.completeTodoEmiter.emit(id);
    }
    editTodo(todo: Todo) {
        this.editTodoEmiter.emit(todo);
    }
      isOverdue(dueDate: Date): boolean {
    if (!dueDate) return false;
    return new Date(dueDate) < new Date();
  }
    navigateToCustomer(id: string) {
        this.navigateToCustomerEmiter.emit(id);
    }
    navigateToContract(id: string) {
        this.navigateToContractEmiter.emit(id);
    }
    navigateToMeter(id: string) {
        this.navigateToMeterEmiter.emit(id);
    }
} 